package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.DeskAreaVo;

/**
 * Entity mapped to table "AREA_ENTITY".
 */
public class AreaEntity {

    private Long id;
    /** Not-null value. */
    private String areaId;
    /** Not-null value. */
    private String areaName;

    public AreaEntity() {
    }

    public AreaEntity(Long id) {
        this.id = id;
    }

    public AreaEntity(Long id, String areaId, String areaName) {
        this.id = id;
        this.areaId = areaId;
        this.areaName = areaName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAreaId() {
        return areaId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /** Not-null value. */
    public String getAreaName() {
        return areaName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public AreaEntity(DeskAreaVo deskArea){
        this.areaId = deskArea.getId();
        this.areaName = deskArea.getName();
    }

    public static ResultObjectBuilder<AreaEntity> builder = new ResultObjectBuilder<AreaEntity>() {
        @Override
        public AreaEntity build(ResultSet rs) throws SQLException {
            AreaEntity areaEntity = new AreaEntity();
            areaEntity.setAreaId(rs.getString("c_id"));
            areaEntity.setAreaName(rs.getString("c_name"));
            return areaEntity;
        }
    };

}
