package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "BILL_ACCOUNT_HISTORY_ENTITY".
 */
public class BillAccountHistoryEntity implements Parcelable {
    private Long id;
    private String billAccountHistoryId;
    private String orderId;
    private String billAccountId;
    private String billAccountName;
    private String billAccountPersonId;
    private String billAccountPersonName;
    private String billAccountUnitId;
    private String billAccountUnitName;
    private String billAccountSignId;
    private String billAccountSignName;
    private Integer billAccountMoney;
    private Long createTime;
    private String orderNo;
    private Integer isJoinOrder;

    public BillAccountHistoryEntity() {
    }

    public BillAccountHistoryEntity(Long id) {
        this.id = id;
    }

    public BillAccountHistoryEntity(Long id, String billAccountHistoryId, String orderId, String billAccountId, String billAccountName, String billAccountPersonId, String billAccountPersonName, String billAccountUnitId, String billAccountUnitName, String billAccountSignId, String billAccountSignName, Integer billAccountMoney, Long createTime, String orderNo, Integer isJoinOrder) {
        this.id = id;
        this.billAccountHistoryId = billAccountHistoryId;
        this.orderId = orderId;
        this.billAccountId = billAccountId;
        this.billAccountName = billAccountName;
        this.billAccountPersonId = billAccountPersonId;
        this.billAccountPersonName = billAccountPersonName;
        this.billAccountUnitId = billAccountUnitId;
        this.billAccountUnitName = billAccountUnitName;
        this.billAccountSignId = billAccountSignId;
        this.billAccountSignName = billAccountSignName;
        this.billAccountMoney = billAccountMoney;
        this.createTime = createTime;
        this.orderNo = orderNo;
        this.isJoinOrder = isJoinOrder;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBillAccountHistoryId() {
        return billAccountHistoryId;
    }

    public void setBillAccountHistoryId(String billAccountHistoryId) {
        this.billAccountHistoryId = billAccountHistoryId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getBillAccountId() {
        return billAccountId;
    }

    public void setBillAccountId(String billAccountId) {
        this.billAccountId = billAccountId;
    }

    public String getBillAccountName() {
        return billAccountName;
    }

    public void setBillAccountName(String billAccountName) {
        this.billAccountName = billAccountName;
    }

    public String getBillAccountPersonId() {
        return billAccountPersonId;
    }

    public void setBillAccountPersonId(String billAccountPersonId) {
        this.billAccountPersonId = billAccountPersonId;
    }

    public String getBillAccountPersonName() {
        return billAccountPersonName;
    }

    public void setBillAccountPersonName(String billAccountPersonName) {
        this.billAccountPersonName = billAccountPersonName;
    }

    public String getBillAccountUnitId() {
        return billAccountUnitId;
    }

    public void setBillAccountUnitId(String billAccountUnitId) {
        this.billAccountUnitId = billAccountUnitId;
    }

    public String getBillAccountUnitName() {
        return billAccountUnitName;
    }

    public void setBillAccountUnitName(String billAccountUnitName) {
        this.billAccountUnitName = billAccountUnitName;
    }

    public String getBillAccountSignId() {
        return billAccountSignId;
    }

    public void setBillAccountSignId(String billAccountSignId) {
        this.billAccountSignId = billAccountSignId;
    }

    public String getBillAccountSignName() {
        return billAccountSignName;
    }

    public void setBillAccountSignName(String billAccountSignName) {
        this.billAccountSignName = billAccountSignName;
    }

    public Integer getBillAccountMoney() {
        return billAccountMoney;
    }

    public void setBillAccountMoney(Integer billAccountMoney) {
        this.billAccountMoney = billAccountMoney;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public Integer getIsJoinOrder() {
        return isJoinOrder;
    }

    public void setIsJoinOrder(Integer isJoinOrder) {
        this.isJoinOrder = isJoinOrder;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.billAccountHistoryId);
        dest.writeString(this.orderId);
        dest.writeString(this.billAccountId);
        dest.writeString(this.billAccountName);
        dest.writeString(this.billAccountPersonId);
        dest.writeString(this.billAccountPersonName);
        dest.writeString(this.billAccountUnitId);
        dest.writeString(this.billAccountUnitName);
        dest.writeString(this.billAccountSignId);
        dest.writeString(this.billAccountSignName);
        dest.writeValue(this.billAccountMoney);
        dest.writeValue(this.createTime);
        dest.writeString(this.orderNo);
        dest.writeValue(this.isJoinOrder);
    }

    protected BillAccountHistoryEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.billAccountHistoryId = in.readString();
        this.orderId = in.readString();
        this.billAccountId = in.readString();
        this.billAccountName = in.readString();
        this.billAccountPersonId = in.readString();
        this.billAccountPersonName = in.readString();
        this.billAccountUnitId = in.readString();
        this.billAccountUnitName = in.readString();
        this.billAccountSignId = in.readString();
        this.billAccountSignName = in.readString();
        this.billAccountMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.createTime = (Long) in.readValue(Long.class.getClassLoader());
        this.orderNo = in.readString();
        this.isJoinOrder = (Integer) in.readValue(Integer.class.getClassLoader());
    }

    public static final Parcelable.Creator<BillAccountHistoryEntity> CREATOR = new Parcelable.Creator<BillAccountHistoryEntity>() {
        @Override
        public BillAccountHistoryEntity createFromParcel(Parcel source) {
            return new BillAccountHistoryEntity(source);
        }

        @Override
        public BillAccountHistoryEntity[] newArray(int size) {
            return new BillAccountHistoryEntity[size];
        }
    };
}
