package jufeng.juyancash.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO four table "BILL_ACCOUNT_PERSON_ENTITY".
*/
public class BillAccountPersonEntityDao extends AbstractDao<BillAccountPersonEntity, Long> {

    public static final String TABLENAME = "BILL_ACCOUNT_PERSON_ENTITY";

    /**
     * Properties of entity BillAccountPersonEntity.<br/>
     * Can be used four QueryBuilder and four referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BillAccountPersonId = new Property(1, String.class, "billAccountPersonId", false, "BILL_ACCOUNT_PERSON_ID");
        public final static Property BillAccountId = new Property(2, String.class, "billAccountId", false, "BILL_ACCOUNT_ID");
        public final static Property BillAccountPersonType = new Property(3, Integer.class, "billAccountPersonType", false, "BILL_ACCOUNT_PERSON_TYPE");
        public final static Property BillAccountPersonName = new Property(4, String.class, "billAccountPersonName", false, "BILL_ACCOUNT_PERSON_NAME");
    }


    public BillAccountPersonEntityDao(DaoConfig config) {
        super(config);
    }
    
    public BillAccountPersonEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BILL_ACCOUNT_PERSON_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"BILL_ACCOUNT_PERSON_ID\" TEXT," + // 1: billAccountPersonId
                "\"BILL_ACCOUNT_ID\" TEXT," + // 2: billAccountId
                "\"BILL_ACCOUNT_PERSON_TYPE\" INTEGER," + // 3: billAccountPersonType
                "\"BILL_ACCOUNT_PERSON_NAME\" TEXT);"); // 4: billAccountPersonName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BILL_ACCOUNT_PERSON_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BillAccountPersonEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String billAccountPersonId = entity.getBillAccountPersonId();
        if (billAccountPersonId != null) {
            stmt.bindString(2, billAccountPersonId);
        }
 
        String billAccountId = entity.getBillAccountId();
        if (billAccountId != null) {
            stmt.bindString(3, billAccountId);
        }
 
        Integer billAccountPersonType = entity.getBillAccountPersonType();
        if (billAccountPersonType != null) {
            stmt.bindLong(4, billAccountPersonType);
        }
 
        String billAccountPersonName = entity.getBillAccountPersonName();
        if (billAccountPersonName != null) {
            stmt.bindString(5, billAccountPersonName);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BillAccountPersonEntity readEntity(Cursor cursor, int offset) {
        BillAccountPersonEntity entity = new BillAccountPersonEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // billAccountPersonId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // billAccountId
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // billAccountPersonType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // billAccountPersonName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BillAccountPersonEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBillAccountPersonId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBillAccountId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBillAccountPersonType(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setBillAccountPersonName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BillAccountPersonEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BillAccountPersonEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
