package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.BillPersonVo;

/**
 * Entity mapped to table "BILL_ACCOUNT_PERSON_ENTITY".
 */
public class BillAccountPersonEntity extends BillPerson{

    private Long id;
    private String billAccountPersonId;
    private String billAccountId;
    private Integer billAccountPersonType;
    private String billAccountPersonName;

    public BillAccountPersonEntity() {
    }

    public BillAccountPersonEntity(Long id) {
        this.id = id;
    }

    public BillAccountPersonEntity(Long id, String billAccountPersonId, String billAccountId, Integer billAccountPersonType, String billAccountPersonName) {
        this.id = id;
        this.billAccountPersonId = billAccountPersonId;
        this.billAccountId = billAccountId;
        this.billAccountPersonType = billAccountPersonType;
        this.billAccountPersonName = billAccountPersonName;
        setName(billAccountPersonName);
        setPersonId(billAccountPersonId);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBillAccountPersonId() {
        return billAccountPersonId;
    }

    public void setBillAccountPersonId(String billAccountPersonId) {
        this.billAccountPersonId = billAccountPersonId;
    }

    public String getBillAccountId() {
        return billAccountId;
    }

    public void setBillAccountId(String billAccountId) {
        this.billAccountId = billAccountId;
    }

    public Integer getBillAccountPersonType() {
        return billAccountPersonType;
    }

    public void setBillAccountPersonType(Integer billAccountPersonType) {
        this.billAccountPersonType = billAccountPersonType;
    }

    public String getBillAccountPersonName() {
        return billAccountPersonName;
    }

    public void setBillAccountPersonName(String billAccountPersonName) {
        this.billAccountPersonName = billAccountPersonName;
    }

    @Override
    public String toString() {
        return "BillAccountPersonEntity{" +
                "id=" + id +
                ", billAccountPersonId='" + billAccountPersonId + '\'' +
                ", billAccountId='" + billAccountId + '\'' +
                ", billAccountPersonType=" + billAccountPersonType +
                ", billAccountPersonName='" + billAccountPersonName + '\'' +
                '}';
    }

    public BillAccountPersonEntity(BillPersonVo billPersonModel){
        this.billAccountPersonId = billPersonModel.getId();
        this.billAccountId = billPersonModel.getBillId();
        this.billAccountPersonName = billPersonModel.getName();
        this.billAccountPersonType = billPersonModel.getType();
    }

    public static ResultObjectBuilder<BillAccountPersonEntity> builder = new ResultObjectBuilder<BillAccountPersonEntity>() {
        @Override
        public BillAccountPersonEntity build(ResultSet rs) throws SQLException {
            BillAccountPersonEntity billAccountPersonEntity = new BillAccountPersonEntity();
            billAccountPersonEntity.setBillAccountPersonId(rs.getString("c_id"));
            billAccountPersonEntity.setBillAccountId(rs.getString("c_bill_id"));
            billAccountPersonEntity.setBillAccountPersonName(rs.getString("c_name"));
            billAccountPersonEntity.setBillAccountPersonType(rs.getInt("c_type"));
            return billAccountPersonEntity;
        }
    };
}
