package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.BillSigerVo;

/**
 * Entity mapped to table "BILL_ACCOUNT_SIGN_ENTITY".
 */
public class BillAccountSignEntity extends BillPerson{

    private Long id;
    private String billAccountSignId;
    private String billAccountId;
    private String billAccountSignName;

    public BillAccountSignEntity() {
    }

    public BillAccountSignEntity(Long id) {
        this.id = id;
    }

    public BillAccountSignEntity(Long id, String billAccountSignId, String billAccountId, String billAccountSignName) {
        this.id = id;
        this.billAccountSignId = billAccountSignId;
        this.billAccountId = billAccountId;
        this.billAccountSignName = billAccountSignName;
        setName(billAccountSignName);
        setPersonId(billAccountSignId);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBillAccountSignId() {
        return billAccountSignId;
    }

    public void setBillAccountSignId(String billAccountSignId) {
        this.billAccountSignId = billAccountSignId;
    }

    public String getBillAccountId() {
        return billAccountId;
    }

    public void setBillAccountId(String billAccountId) {
        this.billAccountId = billAccountId;
    }

    public String getBillAccountSignName() {
        return billAccountSignName;
    }

    public void setBillAccountSignName(String billAccountSignName) {
        this.billAccountSignName = billAccountSignName;
    }

    @Override
    public String toString() {
        return "BillAccountSignEntity{" +
                "id=" + id +
                ", billAccountSignId='" + billAccountSignId + '\'' +
                ", billAccountId='" + billAccountId + '\'' +
                ", billAccountSignName='" + billAccountSignName + '\'' +
                '}';
    }

    public BillAccountSignEntity(BillSigerVo billSigerModel){
        this.billAccountSignId = billSigerModel.getId();
        this.billAccountId = billSigerModel.getBillId();
        this.billAccountSignName = billSigerModel.getName();
    }

    public static ResultObjectBuilder<BillAccountSignEntity> builder = new ResultObjectBuilder<BillAccountSignEntity>() {
        @Override
        public BillAccountSignEntity build(ResultSet rs) throws SQLException {
            BillAccountSignEntity billAccountSignEntity = new BillAccountSignEntity();
            billAccountSignEntity.setBillAccountSignId(rs.getString("c_id"));
            billAccountSignEntity.setBillAccountId(rs.getString("c_bill_id"));
            billAccountSignEntity.setBillAccountSignName(rs.getString("c_name"));
            return billAccountSignEntity;
        }
    };
}
