package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import jufeng.juyancash.bean.VashierGoodsVo;

/**
 * Entity mapped to table "CASHIER_DISH_ENTITY".
 */
public class CashierDishEntity {

    private Long id;
    /** Not-null value. */
    private String cashierDishId;
    private String dishId;
    private String dishName;

    public CashierDishEntity() {
    }

    public CashierDishEntity(Long id) {
        this.id = id;
    }

    public CashierDishEntity(Long id, String cashierDishId, String dishId, String dishName) {
        this.id = id;
        this.cashierDishId = cashierDishId;
        this.dishId = dishId;
        this.dishName = dishName;
    }

    public CashierDishEntity(VashierGoodsVo vo){
        this.cashierDishId = vo.getId();
        this.dishId = vo.getGoodsId();
        this.dishName = vo.getGoodsName();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCashierDishId() {
        return cashierDishId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCashierDishId(String cashierDishId) {
        this.cashierDishId = cashierDishId;
    }

    public String getDishId() {
        return dishId;
    }

    public void setDishId(String dishId) {
        this.dishId = dishId;
    }

    public String getDishName() {
        return dishName;
    }

    public void setDishName(String dishName) {
        this.dishName = dishName;
    }

}
