package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.DisplayVo;

/**
 * Entity mapped to table "CASHIER_DISPLAY_ENTITY".
 */
public class CashierDisplayEntity {

    private Long id;
    private Integer isOrderDisplay;
    private Integer isCheckoutDisplay;
    private String displayImageUrl;

    public CashierDisplayEntity() {
    }

    public CashierDisplayEntity(Long id) {
        this.id = id;
    }

    public CashierDisplayEntity(Long id, Integer isOrderDisplay, Integer isCheckoutDisplay, String displayImageUrl) {
        this.id = id;
        this.isOrderDisplay = isOrderDisplay;
        this.isCheckoutDisplay = isCheckoutDisplay;
        this.displayImageUrl = displayImageUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIsOrderDisplay() {
        return isOrderDisplay;
    }

    public void setIsOrderDisplay(Integer isOrderDisplay) {
        this.isOrderDisplay = isOrderDisplay;
    }

    public Integer getIsCheckoutDisplay() {
        return isCheckoutDisplay;
    }

    public void setIsCheckoutDisplay(Integer isCheckoutDisplay) {
        this.isCheckoutDisplay = isCheckoutDisplay;
    }

    public String getDisplayImageUrl() {
        return displayImageUrl;
    }

    public void setDisplayImageUrl(String displayImageUrl) {
        this.displayImageUrl = displayImageUrl;
    }

    public CashierDisplayEntity(DisplayVo display){
        this.isOrderDisplay = display.getFood();
        this.isCheckoutDisplay = display.getCheckout();
        this.displayImageUrl = display.getImage();
        Log.d("###", "客显: "+toString());
    }

    @Override
    public String toString() {
        return "CashierDisplayEntity{" +
                "id=" + id +
                ", isOrderDisplay=" + isOrderDisplay +
                ", isCheckoutDisplay=" + isCheckoutDisplay +
                ", displayImageUrl='" + displayImageUrl + '\'' +
                '}';
    }

    public static ResultObjectBuilder<CashierDisplayEntity> builder = new ResultObjectBuilder<CashierDisplayEntity>() {
        @Override
        public CashierDisplayEntity build(ResultSet rs) throws SQLException {
            CashierDisplayEntity cashierDisplayEntity = new CashierDisplayEntity();
            cashierDisplayEntity.setIsOrderDisplay(rs.getInt("c_food"));
            cashierDisplayEntity.setIsCheckoutDisplay(rs.getInt("c_checkout"));
            cashierDisplayEntity.setDisplayImageUrl(rs.getString("c_image"));
            return cashierDisplayEntity;
        }
    };

}
