package jufeng.juyancash.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig areaEntityDaoConfig;
    private final DaoConfig arrangeEntityDaoConfig;
    private final DaoConfig dishEntityDaoConfig;
    private final DaoConfig dishTypeEntityDaoConfig;
    private final DaoConfig employeeEntityDaoConfig;
    private final DaoConfig kichenDishEntityDaoConfig;
    private final DaoConfig kichenPrintEntityDaoConfig;
    private final DaoConfig kitchenDishTypeEntityDaoConfig;
    private final DaoConfig kitchenDisPrintEntityDaoConfig;
    private final DaoConfig orderDishEntityDaoConfig;
    private final DaoConfig orderEntityDaoConfig;
    private final DaoConfig payModeEntityDaoConfig;
    private final DaoConfig permissionEntityDaoConfig;
    private final DaoConfig practiceEntityDaoConfig;
    private final DaoConfig dishPracticeEntityDaoConfig;
    private final DaoConfig rankEntityDaoConfig;
    private final DaoConfig rankPermissionEntityDaoConfig;
    private final DaoConfig roomEntityDaoConfig;
    private final DaoConfig scheduleEntityDaoConfig;
    private final DaoConfig sellCheckEntityDaoConfig;
    private final DaoConfig tableEntityDaoConfig;
    private final DaoConfig taocanEntityDaoConfig;
    private final DaoConfig taocanGroupDishEntityDaoConfig;
    private final DaoConfig taocanGroupEntityDaoConfig;
    private final DaoConfig taocanTypeEntityDaoConfig;
    private final DaoConfig specifyEntityDaoConfig;
    private final DaoConfig dishSpecifyEntityDaoConfig;
    private final DaoConfig takeOutOrderEntityDaoConfig;
    private final DaoConfig cashierDisplayEntityDaoConfig;
    private final DaoConfig specialEntityDaoConfig;
    private final DaoConfig mantissaEntityDaoConfig;
    private final DaoConfig suplusEntityDaoConfig;
    private final DaoConfig grouponEntityDaoConfig;
    private final DaoConfig grouponTaocanEntityDaoConfig;
    private final DaoConfig discountEntityDaoConfig;
    private final DaoConfig dishTypeDiscountEntityDaoConfig;
    private final DaoConfig printCashierEntityDaoConfig;
    private final DaoConfig cashierClassifyEntityDaoConfig;
    private final DaoConfig cashierDishEntityDaoConfig;
    private final DaoConfig printKitchenEntityDaoConfig;
    private final DaoConfig printKitchenClassifyEntityDaoConfig;
    private final DaoConfig printKitchenDishEntityDaoConfig;
    private final DaoConfig standbyPrinterEntityDaoConfig;
    private final DaoConfig printRemarkEntityDaoConfig;
    private final DaoConfig basicsPartnerEntityDaoConfig;
    private final DaoConfig shopMealsEntityDaoConfig;
    private final DaoConfig shopPaymentEntityDaoConfig;
    private final DaoConfig shopReceivableEntityDaoConfig;
    private final DaoConfig shopTimeEntityDaoConfig;
    private final DaoConfig systemMessageEntityDaoConfig;
    private final DaoConfig wXMessageEntityDaoConfig;
    private final DaoConfig storeMessageEntityDaoConfig;
    private final DaoConfig discountHistoryEntityDaoConfig;
    private final DaoConfig someDiscountGoodsEntityDaoConfig;
    private final DaoConfig orderTaocanGroupDishEntityDaoConfig;
    private final DaoConfig printerFailedHistoryEntityDaoConfig;
    private final DaoConfig jpushMessageEntityDaoConfig;
    private final DaoConfig billAccountEntityDaoConfig;
    private final DaoConfig billAccountPersonEntityDaoConfig;
    private final DaoConfig billAccountSignEntityDaoConfig;
    private final DaoConfig billAccountHistoryEntityDaoConfig;
    private final DaoConfig uploadDataEntityDaoConfig;
    private final DaoConfig vipCardEntityDaoConfig;
    private final DaoConfig wxOrderMessageEntityDaoConfig;
    private final DaoConfig printResultEntityDaoConfig;
    private final DaoConfig turnoverHistoryEntityDaoConfig;
    private final DaoConfig tableCodeEntityDaoConfig;
    private final DaoConfig sendPersonEntityDaoConfig;
    private final DaoConfig materialEntityDaoConfig;
    private final DaoConfig dishTypeMaterialEntityDaoConfig;
    private final DaoConfig dishSelectedMaterialEntityDaoConfig;

    private final AreaEntityDao areaEntityDao;
    private final ArrangeEntityDao arrangeEntityDao;
    private final DishEntityDao dishEntityDao;
    private final DishTypeEntityDao dishTypeEntityDao;
    private final EmployeeEntityDao employeeEntityDao;
    private final KichenDishEntityDao kichenDishEntityDao;
    private final KichenPrintEntityDao kichenPrintEntityDao;
    private final KitchenDishTypeEntityDao kitchenDishTypeEntityDao;
    private final KitchenDisPrintEntityDao kitchenDisPrintEntityDao;
    private final OrderDishEntityDao orderDishEntityDao;
    private final OrderEntityDao orderEntityDao;
    private final PayModeEntityDao payModeEntityDao;
    private final PermissionEntityDao permissionEntityDao;
    private final PracticeEntityDao practiceEntityDao;
    private final DishPracticeEntityDao dishPracticeEntityDao;
    private final RankEntityDao rankEntityDao;
    private final RankPermissionEntityDao rankPermissionEntityDao;
    private final RoomEntityDao roomEntityDao;
    private final ScheduleEntityDao scheduleEntityDao;
    private final SellCheckEntityDao sellCheckEntityDao;
    private final TableEntityDao tableEntityDao;
    private final TaocanEntityDao taocanEntityDao;
    private final TaocanGroupDishEntityDao taocanGroupDishEntityDao;
    private final TaocanGroupEntityDao taocanGroupEntityDao;
    private final TaocanTypeEntityDao taocanTypeEntityDao;
    private final SpecifyEntityDao specifyEntityDao;
    private final DishSpecifyEntityDao dishSpecifyEntityDao;
    private final TakeOutOrderEntityDao takeOutOrderEntityDao;
    private final CashierDisplayEntityDao cashierDisplayEntityDao;
    private final SpecialEntityDao specialEntityDao;
    private final MantissaEntityDao mantissaEntityDao;
    private final SuplusEntityDao suplusEntityDao;
    private final GrouponEntityDao grouponEntityDao;
    private final GrouponTaocanEntityDao grouponTaocanEntityDao;
    private final DiscountEntityDao discountEntityDao;
    private final DishTypeDiscountEntityDao dishTypeDiscountEntityDao;
    private final PrintCashierEntityDao printCashierEntityDao;
    private final CashierClassifyEntityDao cashierClassifyEntityDao;
    private final CashierDishEntityDao cashierDishEntityDao;
    private final PrintKitchenEntityDao printKitchenEntityDao;
    private final PrintKitchenClassifyEntityDao printKitchenClassifyEntityDao;
    private final PrintKitchenDishEntityDao printKitchenDishEntityDao;
    private final StandbyPrinterEntityDao standbyPrinterEntityDao;
    private final PrintRemarkEntityDao printRemarkEntityDao;
    private final BasicsPartnerEntityDao basicsPartnerEntityDao;
    private final ShopMealsEntityDao shopMealsEntityDao;
    private final ShopPaymentEntityDao shopPaymentEntityDao;
    private final ShopReceivableEntityDao shopReceivableEntityDao;
    private final ShopTimeEntityDao shopTimeEntityDao;
    private final SystemMessageEntityDao systemMessageEntityDao;
    private final WXMessageEntityDao wXMessageEntityDao;
    private final StoreMessageEntityDao storeMessageEntityDao;
    private final DiscountHistoryEntityDao discountHistoryEntityDao;
    private final SomeDiscountGoodsEntityDao someDiscountGoodsEntityDao;
    private final OrderTaocanGroupDishEntityDao orderTaocanGroupDishEntityDao;
    private final PrinterFailedHistoryEntityDao printerFailedHistoryEntityDao;
    private final JpushMessageEntityDao jpushMessageEntityDao;
    private final BillAccountEntityDao billAccountEntityDao;
    private final BillAccountPersonEntityDao billAccountPersonEntityDao;
    private final BillAccountSignEntityDao billAccountSignEntityDao;
    private final BillAccountHistoryEntityDao billAccountHistoryEntityDao;
    private final UploadDataEntityDao uploadDataEntityDao;
    private final VipCardEntityDao vipCardEntityDao;
    private final WxOrderMessageEntityDao wxOrderMessageEntityDao;
    private final PrintResultEntityDao printResultEntityDao;
    private final TurnoverHistoryEntityDao turnoverHistoryEntityDao;
    private final TableCodeEntityDao tableCodeEntityDao;
    private final SendPersonEntityDao sendPersonEntityDao;
    private final MaterialEntityDao materialEntityDao;
    private final DishTypeMaterialEntityDao dishTypeMaterialEntityDao;
    private final DishSelectedMaterialEntityDao dishSelectedMaterialEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        areaEntityDaoConfig = daoConfigMap.get(AreaEntityDao.class).clone();
        areaEntityDaoConfig.initIdentityScope(type);

        arrangeEntityDaoConfig = daoConfigMap.get(ArrangeEntityDao.class).clone();
        arrangeEntityDaoConfig.initIdentityScope(type);

        dishEntityDaoConfig = daoConfigMap.get(DishEntityDao.class).clone();
        dishEntityDaoConfig.initIdentityScope(type);

        dishTypeEntityDaoConfig = daoConfigMap.get(DishTypeEntityDao.class).clone();
        dishTypeEntityDaoConfig.initIdentityScope(type);

        employeeEntityDaoConfig = daoConfigMap.get(EmployeeEntityDao.class).clone();
        employeeEntityDaoConfig.initIdentityScope(type);

        kichenDishEntityDaoConfig = daoConfigMap.get(KichenDishEntityDao.class).clone();
        kichenDishEntityDaoConfig.initIdentityScope(type);

        kichenPrintEntityDaoConfig = daoConfigMap.get(KichenPrintEntityDao.class).clone();
        kichenPrintEntityDaoConfig.initIdentityScope(type);

        kitchenDishTypeEntityDaoConfig = daoConfigMap.get(KitchenDishTypeEntityDao.class).clone();
        kitchenDishTypeEntityDaoConfig.initIdentityScope(type);

        kitchenDisPrintEntityDaoConfig = daoConfigMap.get(KitchenDisPrintEntityDao.class).clone();
        kitchenDisPrintEntityDaoConfig.initIdentityScope(type);

        orderDishEntityDaoConfig = daoConfigMap.get(OrderDishEntityDao.class).clone();
        orderDishEntityDaoConfig.initIdentityScope(type);

        orderEntityDaoConfig = daoConfigMap.get(OrderEntityDao.class).clone();
        orderEntityDaoConfig.initIdentityScope(type);

        payModeEntityDaoConfig = daoConfigMap.get(PayModeEntityDao.class).clone();
        payModeEntityDaoConfig.initIdentityScope(type);

        permissionEntityDaoConfig = daoConfigMap.get(PermissionEntityDao.class).clone();
        permissionEntityDaoConfig.initIdentityScope(type);

        practiceEntityDaoConfig = daoConfigMap.get(PracticeEntityDao.class).clone();
        practiceEntityDaoConfig.initIdentityScope(type);

        dishPracticeEntityDaoConfig = daoConfigMap.get(DishPracticeEntityDao.class).clone();
        dishPracticeEntityDaoConfig.initIdentityScope(type);

        rankEntityDaoConfig = daoConfigMap.get(RankEntityDao.class).clone();
        rankEntityDaoConfig.initIdentityScope(type);

        rankPermissionEntityDaoConfig = daoConfigMap.get(RankPermissionEntityDao.class).clone();
        rankPermissionEntityDaoConfig.initIdentityScope(type);

        roomEntityDaoConfig = daoConfigMap.get(RoomEntityDao.class).clone();
        roomEntityDaoConfig.initIdentityScope(type);

        scheduleEntityDaoConfig = daoConfigMap.get(ScheduleEntityDao.class).clone();
        scheduleEntityDaoConfig.initIdentityScope(type);

        sellCheckEntityDaoConfig = daoConfigMap.get(SellCheckEntityDao.class).clone();
        sellCheckEntityDaoConfig.initIdentityScope(type);

        tableEntityDaoConfig = daoConfigMap.get(TableEntityDao.class).clone();
        tableEntityDaoConfig.initIdentityScope(type);

        taocanEntityDaoConfig = daoConfigMap.get(TaocanEntityDao.class).clone();
        taocanEntityDaoConfig.initIdentityScope(type);

        taocanGroupDishEntityDaoConfig = daoConfigMap.get(TaocanGroupDishEntityDao.class).clone();
        taocanGroupDishEntityDaoConfig.initIdentityScope(type);

        taocanGroupEntityDaoConfig = daoConfigMap.get(TaocanGroupEntityDao.class).clone();
        taocanGroupEntityDaoConfig.initIdentityScope(type);

        taocanTypeEntityDaoConfig = daoConfigMap.get(TaocanTypeEntityDao.class).clone();
        taocanTypeEntityDaoConfig.initIdentityScope(type);

        specifyEntityDaoConfig = daoConfigMap.get(SpecifyEntityDao.class).clone();
        specifyEntityDaoConfig.initIdentityScope(type);

        dishSpecifyEntityDaoConfig = daoConfigMap.get(DishSpecifyEntityDao.class).clone();
        dishSpecifyEntityDaoConfig.initIdentityScope(type);

        takeOutOrderEntityDaoConfig = daoConfigMap.get(TakeOutOrderEntityDao.class).clone();
        takeOutOrderEntityDaoConfig.initIdentityScope(type);

        cashierDisplayEntityDaoConfig = daoConfigMap.get(CashierDisplayEntityDao.class).clone();
        cashierDisplayEntityDaoConfig.initIdentityScope(type);

        specialEntityDaoConfig = daoConfigMap.get(SpecialEntityDao.class).clone();
        specialEntityDaoConfig.initIdentityScope(type);

        mantissaEntityDaoConfig = daoConfigMap.get(MantissaEntityDao.class).clone();
        mantissaEntityDaoConfig.initIdentityScope(type);

        suplusEntityDaoConfig = daoConfigMap.get(SuplusEntityDao.class).clone();
        suplusEntityDaoConfig.initIdentityScope(type);

        grouponEntityDaoConfig = daoConfigMap.get(GrouponEntityDao.class).clone();
        grouponEntityDaoConfig.initIdentityScope(type);

        grouponTaocanEntityDaoConfig = daoConfigMap.get(GrouponTaocanEntityDao.class).clone();
        grouponTaocanEntityDaoConfig.initIdentityScope(type);

        discountEntityDaoConfig = daoConfigMap.get(DiscountEntityDao.class).clone();
        discountEntityDaoConfig.initIdentityScope(type);

        dishTypeDiscountEntityDaoConfig = daoConfigMap.get(DishTypeDiscountEntityDao.class).clone();
        dishTypeDiscountEntityDaoConfig.initIdentityScope(type);

        printCashierEntityDaoConfig = daoConfigMap.get(PrintCashierEntityDao.class).clone();
        printCashierEntityDaoConfig.initIdentityScope(type);

        cashierClassifyEntityDaoConfig = daoConfigMap.get(CashierClassifyEntityDao.class).clone();
        cashierClassifyEntityDaoConfig.initIdentityScope(type);

        cashierDishEntityDaoConfig = daoConfigMap.get(CashierDishEntityDao.class).clone();
        cashierDishEntityDaoConfig.initIdentityScope(type);

        printKitchenEntityDaoConfig = daoConfigMap.get(PrintKitchenEntityDao.class).clone();
        printKitchenEntityDaoConfig.initIdentityScope(type);

        printKitchenClassifyEntityDaoConfig = daoConfigMap.get(PrintKitchenClassifyEntityDao.class).clone();
        printKitchenClassifyEntityDaoConfig.initIdentityScope(type);

        printKitchenDishEntityDaoConfig = daoConfigMap.get(PrintKitchenDishEntityDao.class).clone();
        printKitchenDishEntityDaoConfig.initIdentityScope(type);

        standbyPrinterEntityDaoConfig = daoConfigMap.get(StandbyPrinterEntityDao.class).clone();
        standbyPrinterEntityDaoConfig.initIdentityScope(type);

        printRemarkEntityDaoConfig = daoConfigMap.get(PrintRemarkEntityDao.class).clone();
        printRemarkEntityDaoConfig.initIdentityScope(type);

        basicsPartnerEntityDaoConfig = daoConfigMap.get(BasicsPartnerEntityDao.class).clone();
        basicsPartnerEntityDaoConfig.initIdentityScope(type);

        shopMealsEntityDaoConfig = daoConfigMap.get(ShopMealsEntityDao.class).clone();
        shopMealsEntityDaoConfig.initIdentityScope(type);

        shopPaymentEntityDaoConfig = daoConfigMap.get(ShopPaymentEntityDao.class).clone();
        shopPaymentEntityDaoConfig.initIdentityScope(type);

        shopReceivableEntityDaoConfig = daoConfigMap.get(ShopReceivableEntityDao.class).clone();
        shopReceivableEntityDaoConfig.initIdentityScope(type);

        shopTimeEntityDaoConfig = daoConfigMap.get(ShopTimeEntityDao.class).clone();
        shopTimeEntityDaoConfig.initIdentityScope(type);

        systemMessageEntityDaoConfig = daoConfigMap.get(SystemMessageEntityDao.class).clone();
        systemMessageEntityDaoConfig.initIdentityScope(type);

        wXMessageEntityDaoConfig = daoConfigMap.get(WXMessageEntityDao.class).clone();
        wXMessageEntityDaoConfig.initIdentityScope(type);

        storeMessageEntityDaoConfig = daoConfigMap.get(StoreMessageEntityDao.class).clone();
        storeMessageEntityDaoConfig.initIdentityScope(type);

        discountHistoryEntityDaoConfig = daoConfigMap.get(DiscountHistoryEntityDao.class).clone();
        discountHistoryEntityDaoConfig.initIdentityScope(type);

        someDiscountGoodsEntityDaoConfig = daoConfigMap.get(SomeDiscountGoodsEntityDao.class).clone();
        someDiscountGoodsEntityDaoConfig.initIdentityScope(type);

        orderTaocanGroupDishEntityDaoConfig = daoConfigMap.get(OrderTaocanGroupDishEntityDao.class).clone();
        orderTaocanGroupDishEntityDaoConfig.initIdentityScope(type);

        printerFailedHistoryEntityDaoConfig = daoConfigMap.get(PrinterFailedHistoryEntityDao.class).clone();
        printerFailedHistoryEntityDaoConfig.initIdentityScope(type);

        jpushMessageEntityDaoConfig = daoConfigMap.get(JpushMessageEntityDao.class).clone();
        jpushMessageEntityDaoConfig.initIdentityScope(type);

        billAccountEntityDaoConfig = daoConfigMap.get(BillAccountEntityDao.class).clone();
        billAccountEntityDaoConfig.initIdentityScope(type);

        billAccountPersonEntityDaoConfig = daoConfigMap.get(BillAccountPersonEntityDao.class).clone();
        billAccountPersonEntityDaoConfig.initIdentityScope(type);

        billAccountSignEntityDaoConfig = daoConfigMap.get(BillAccountSignEntityDao.class).clone();
        billAccountSignEntityDaoConfig.initIdentityScope(type);

        billAccountHistoryEntityDaoConfig = daoConfigMap.get(BillAccountHistoryEntityDao.class).clone();
        billAccountHistoryEntityDaoConfig.initIdentityScope(type);

        uploadDataEntityDaoConfig = daoConfigMap.get(UploadDataEntityDao.class).clone();
        uploadDataEntityDaoConfig.initIdentityScope(type);

        vipCardEntityDaoConfig = daoConfigMap.get(VipCardEntityDao.class).clone();
        vipCardEntityDaoConfig.initIdentityScope(type);

        wxOrderMessageEntityDaoConfig = daoConfigMap.get(WxOrderMessageEntityDao.class).clone();
        wxOrderMessageEntityDaoConfig.initIdentityScope(type);

        printResultEntityDaoConfig = daoConfigMap.get(PrintResultEntityDao.class).clone();
        printResultEntityDaoConfig.initIdentityScope(type);

        turnoverHistoryEntityDaoConfig = daoConfigMap.get(TurnoverHistoryEntityDao.class).clone();
        turnoverHistoryEntityDaoConfig.initIdentityScope(type);

        tableCodeEntityDaoConfig = daoConfigMap.get(TableCodeEntityDao.class).clone();
        tableCodeEntityDaoConfig.initIdentityScope(type);

        sendPersonEntityDaoConfig = daoConfigMap.get(SendPersonEntityDao.class).clone();
        sendPersonEntityDaoConfig.initIdentityScope(type);

        materialEntityDaoConfig = daoConfigMap.get(MaterialEntityDao.class).clone();
        materialEntityDaoConfig.initIdentityScope(type);

        dishTypeMaterialEntityDaoConfig = daoConfigMap.get(DishTypeMaterialEntityDao.class).clone();
        dishTypeMaterialEntityDaoConfig.initIdentityScope(type);

        dishSelectedMaterialEntityDaoConfig = daoConfigMap.get(DishSelectedMaterialEntityDao.class).clone();
        dishSelectedMaterialEntityDaoConfig.initIdentityScope(type);

        areaEntityDao = new AreaEntityDao(areaEntityDaoConfig, this);
        arrangeEntityDao = new ArrangeEntityDao(arrangeEntityDaoConfig, this);
        dishEntityDao = new DishEntityDao(dishEntityDaoConfig, this);
        dishTypeEntityDao = new DishTypeEntityDao(dishTypeEntityDaoConfig, this);
        employeeEntityDao = new EmployeeEntityDao(employeeEntityDaoConfig, this);
        kichenDishEntityDao = new KichenDishEntityDao(kichenDishEntityDaoConfig, this);
        kichenPrintEntityDao = new KichenPrintEntityDao(kichenPrintEntityDaoConfig, this);
        kitchenDishTypeEntityDao = new KitchenDishTypeEntityDao(kitchenDishTypeEntityDaoConfig, this);
        kitchenDisPrintEntityDao = new KitchenDisPrintEntityDao(kitchenDisPrintEntityDaoConfig, this);
        orderDishEntityDao = new OrderDishEntityDao(orderDishEntityDaoConfig, this);
        orderEntityDao = new OrderEntityDao(orderEntityDaoConfig, this);
        payModeEntityDao = new PayModeEntityDao(payModeEntityDaoConfig, this);
        permissionEntityDao = new PermissionEntityDao(permissionEntityDaoConfig, this);
        practiceEntityDao = new PracticeEntityDao(practiceEntityDaoConfig, this);
        dishPracticeEntityDao = new DishPracticeEntityDao(dishPracticeEntityDaoConfig, this);
        rankEntityDao = new RankEntityDao(rankEntityDaoConfig, this);
        rankPermissionEntityDao = new RankPermissionEntityDao(rankPermissionEntityDaoConfig, this);
        roomEntityDao = new RoomEntityDao(roomEntityDaoConfig, this);
        scheduleEntityDao = new ScheduleEntityDao(scheduleEntityDaoConfig, this);
        sellCheckEntityDao = new SellCheckEntityDao(sellCheckEntityDaoConfig, this);
        tableEntityDao = new TableEntityDao(tableEntityDaoConfig, this);
        taocanEntityDao = new TaocanEntityDao(taocanEntityDaoConfig, this);
        taocanGroupDishEntityDao = new TaocanGroupDishEntityDao(taocanGroupDishEntityDaoConfig, this);
        taocanGroupEntityDao = new TaocanGroupEntityDao(taocanGroupEntityDaoConfig, this);
        taocanTypeEntityDao = new TaocanTypeEntityDao(taocanTypeEntityDaoConfig, this);
        specifyEntityDao = new SpecifyEntityDao(specifyEntityDaoConfig, this);
        dishSpecifyEntityDao = new DishSpecifyEntityDao(dishSpecifyEntityDaoConfig, this);
        takeOutOrderEntityDao = new TakeOutOrderEntityDao(takeOutOrderEntityDaoConfig, this);
        cashierDisplayEntityDao = new CashierDisplayEntityDao(cashierDisplayEntityDaoConfig, this);
        specialEntityDao = new SpecialEntityDao(specialEntityDaoConfig, this);
        mantissaEntityDao = new MantissaEntityDao(mantissaEntityDaoConfig, this);
        suplusEntityDao = new SuplusEntityDao(suplusEntityDaoConfig, this);
        grouponEntityDao = new GrouponEntityDao(grouponEntityDaoConfig, this);
        grouponTaocanEntityDao = new GrouponTaocanEntityDao(grouponTaocanEntityDaoConfig, this);
        discountEntityDao = new DiscountEntityDao(discountEntityDaoConfig, this);
        dishTypeDiscountEntityDao = new DishTypeDiscountEntityDao(dishTypeDiscountEntityDaoConfig, this);
        printCashierEntityDao = new PrintCashierEntityDao(printCashierEntityDaoConfig, this);
        cashierClassifyEntityDao = new CashierClassifyEntityDao(cashierClassifyEntityDaoConfig, this);
        cashierDishEntityDao = new CashierDishEntityDao(cashierDishEntityDaoConfig, this);
        printKitchenEntityDao = new PrintKitchenEntityDao(printKitchenEntityDaoConfig, this);
        printKitchenClassifyEntityDao = new PrintKitchenClassifyEntityDao(printKitchenClassifyEntityDaoConfig, this);
        printKitchenDishEntityDao = new PrintKitchenDishEntityDao(printKitchenDishEntityDaoConfig, this);
        standbyPrinterEntityDao = new StandbyPrinterEntityDao(standbyPrinterEntityDaoConfig, this);
        printRemarkEntityDao = new PrintRemarkEntityDao(printRemarkEntityDaoConfig, this);
        basicsPartnerEntityDao = new BasicsPartnerEntityDao(basicsPartnerEntityDaoConfig, this);
        shopMealsEntityDao = new ShopMealsEntityDao(shopMealsEntityDaoConfig, this);
        shopPaymentEntityDao = new ShopPaymentEntityDao(shopPaymentEntityDaoConfig, this);
        shopReceivableEntityDao = new ShopReceivableEntityDao(shopReceivableEntityDaoConfig, this);
        shopTimeEntityDao = new ShopTimeEntityDao(shopTimeEntityDaoConfig, this);
        systemMessageEntityDao = new SystemMessageEntityDao(systemMessageEntityDaoConfig, this);
        wXMessageEntityDao = new WXMessageEntityDao(wXMessageEntityDaoConfig, this);
        storeMessageEntityDao = new StoreMessageEntityDao(storeMessageEntityDaoConfig, this);
        discountHistoryEntityDao = new DiscountHistoryEntityDao(discountHistoryEntityDaoConfig, this);
        someDiscountGoodsEntityDao = new SomeDiscountGoodsEntityDao(someDiscountGoodsEntityDaoConfig, this);
        orderTaocanGroupDishEntityDao = new OrderTaocanGroupDishEntityDao(orderTaocanGroupDishEntityDaoConfig, this);
        printerFailedHistoryEntityDao = new PrinterFailedHistoryEntityDao(printerFailedHistoryEntityDaoConfig, this);
        jpushMessageEntityDao = new JpushMessageEntityDao(jpushMessageEntityDaoConfig, this);
        billAccountEntityDao = new BillAccountEntityDao(billAccountEntityDaoConfig, this);
        billAccountPersonEntityDao = new BillAccountPersonEntityDao(billAccountPersonEntityDaoConfig, this);
        billAccountSignEntityDao = new BillAccountSignEntityDao(billAccountSignEntityDaoConfig, this);
        billAccountHistoryEntityDao = new BillAccountHistoryEntityDao(billAccountHistoryEntityDaoConfig, this);
        uploadDataEntityDao = new UploadDataEntityDao(uploadDataEntityDaoConfig, this);
        vipCardEntityDao = new VipCardEntityDao(vipCardEntityDaoConfig, this);
        wxOrderMessageEntityDao = new WxOrderMessageEntityDao(wxOrderMessageEntityDaoConfig, this);
        printResultEntityDao = new PrintResultEntityDao(printResultEntityDaoConfig, this);
        turnoverHistoryEntityDao = new TurnoverHistoryEntityDao(turnoverHistoryEntityDaoConfig, this);
        tableCodeEntityDao = new TableCodeEntityDao(tableCodeEntityDaoConfig, this);
        sendPersonEntityDao = new SendPersonEntityDao(sendPersonEntityDaoConfig, this);
        materialEntityDao = new MaterialEntityDao(materialEntityDaoConfig, this);
        dishTypeMaterialEntityDao = new DishTypeMaterialEntityDao(dishTypeMaterialEntityDaoConfig, this);
        dishSelectedMaterialEntityDao = new DishSelectedMaterialEntityDao(dishSelectedMaterialEntityDaoConfig, this);

        registerDao(AreaEntity.class, areaEntityDao);
        registerDao(ArrangeEntity.class, arrangeEntityDao);
        registerDao(DishEntity.class, dishEntityDao);
        registerDao(DishTypeEntity.class, dishTypeEntityDao);
        registerDao(EmployeeEntity.class, employeeEntityDao);
        registerDao(KichenDishEntity.class, kichenDishEntityDao);
        registerDao(KichenPrintEntity.class, kichenPrintEntityDao);
        registerDao(KitchenDishTypeEntity.class, kitchenDishTypeEntityDao);
        registerDao(KitchenDisPrintEntity.class, kitchenDisPrintEntityDao);
        registerDao(OrderDishEntity.class, orderDishEntityDao);
        registerDao(OrderEntity.class, orderEntityDao);
        registerDao(PayModeEntity.class, payModeEntityDao);
        registerDao(PermissionEntity.class, permissionEntityDao);
        registerDao(PracticeEntity.class, practiceEntityDao);
        registerDao(DishPracticeEntity.class, dishPracticeEntityDao);
        registerDao(RankEntity.class, rankEntityDao);
        registerDao(RankPermissionEntity.class, rankPermissionEntityDao);
        registerDao(RoomEntity.class, roomEntityDao);
        registerDao(ScheduleEntity.class, scheduleEntityDao);
        registerDao(SellCheckEntity.class, sellCheckEntityDao);
        registerDao(TableEntity.class, tableEntityDao);
        registerDao(TaocanEntity.class, taocanEntityDao);
        registerDao(TaocanGroupDishEntity.class, taocanGroupDishEntityDao);
        registerDao(TaocanGroupEntity.class, taocanGroupEntityDao);
        registerDao(TaocanTypeEntity.class, taocanTypeEntityDao);
        registerDao(SpecifyEntity.class, specifyEntityDao);
        registerDao(DishSpecifyEntity.class, dishSpecifyEntityDao);
        registerDao(TakeOutOrderEntity.class, takeOutOrderEntityDao);
        registerDao(CashierDisplayEntity.class, cashierDisplayEntityDao);
        registerDao(SpecialEntity.class, specialEntityDao);
        registerDao(MantissaEntity.class, mantissaEntityDao);
        registerDao(SuplusEntity.class, suplusEntityDao);
        registerDao(GrouponEntity.class, grouponEntityDao);
        registerDao(GrouponTaocanEntity.class, grouponTaocanEntityDao);
        registerDao(DiscountEntity.class, discountEntityDao);
        registerDao(DishTypeDiscountEntity.class, dishTypeDiscountEntityDao);
        registerDao(PrintCashierEntity.class, printCashierEntityDao);
        registerDao(CashierClassifyEntity.class, cashierClassifyEntityDao);
        registerDao(CashierDishEntity.class, cashierDishEntityDao);
        registerDao(PrintKitchenEntity.class, printKitchenEntityDao);
        registerDao(PrintKitchenClassifyEntity.class, printKitchenClassifyEntityDao);
        registerDao(PrintKitchenDishEntity.class, printKitchenDishEntityDao);
        registerDao(StandbyPrinterEntity.class, standbyPrinterEntityDao);
        registerDao(PrintRemarkEntity.class, printRemarkEntityDao);
        registerDao(BasicsPartnerEntity.class, basicsPartnerEntityDao);
        registerDao(ShopMealsEntity.class, shopMealsEntityDao);
        registerDao(ShopPaymentEntity.class, shopPaymentEntityDao);
        registerDao(ShopReceivableEntity.class, shopReceivableEntityDao);
        registerDao(ShopTimeEntity.class, shopTimeEntityDao);
        registerDao(SystemMessageEntity.class, systemMessageEntityDao);
        registerDao(WXMessageEntity.class, wXMessageEntityDao);
        registerDao(StoreMessageEntity.class, storeMessageEntityDao);
        registerDao(DiscountHistoryEntity.class, discountHistoryEntityDao);
        registerDao(SomeDiscountGoodsEntity.class, someDiscountGoodsEntityDao);
        registerDao(OrderTaocanGroupDishEntity.class, orderTaocanGroupDishEntityDao);
        registerDao(PrinterFailedHistoryEntity.class, printerFailedHistoryEntityDao);
        registerDao(JpushMessageEntity.class, jpushMessageEntityDao);
        registerDao(BillAccountEntity.class, billAccountEntityDao);
        registerDao(BillAccountPersonEntity.class, billAccountPersonEntityDao);
        registerDao(BillAccountSignEntity.class, billAccountSignEntityDao);
        registerDao(BillAccountHistoryEntity.class, billAccountHistoryEntityDao);
        registerDao(UploadDataEntity.class, uploadDataEntityDao);
        registerDao(VipCardEntity.class, vipCardEntityDao);
        registerDao(WxOrderMessageEntity.class, wxOrderMessageEntityDao);
        registerDao(PrintResultEntity.class, printResultEntityDao);
        registerDao(TurnoverHistoryEntity.class, turnoverHistoryEntityDao);
        registerDao(TableCodeEntity.class, tableCodeEntityDao);
        registerDao(SendPersonEntity.class, sendPersonEntityDao);
        registerDao(MaterialEntity.class, materialEntityDao);
        registerDao(DishTypeMaterialEntity.class, dishTypeMaterialEntityDao);
        registerDao(DishSelectedMaterialEntity.class, dishSelectedMaterialEntityDao);
    }
    
    public void clear() {
        areaEntityDaoConfig.getIdentityScope().clear();
        arrangeEntityDaoConfig.getIdentityScope().clear();
        dishEntityDaoConfig.getIdentityScope().clear();
        dishTypeEntityDaoConfig.getIdentityScope().clear();
        employeeEntityDaoConfig.getIdentityScope().clear();
        kichenDishEntityDaoConfig.getIdentityScope().clear();
        kichenPrintEntityDaoConfig.getIdentityScope().clear();
        kitchenDishTypeEntityDaoConfig.getIdentityScope().clear();
        kitchenDisPrintEntityDaoConfig.getIdentityScope().clear();
        orderDishEntityDaoConfig.getIdentityScope().clear();
        orderEntityDaoConfig.getIdentityScope().clear();
        payModeEntityDaoConfig.getIdentityScope().clear();
        permissionEntityDaoConfig.getIdentityScope().clear();
        practiceEntityDaoConfig.getIdentityScope().clear();
        dishPracticeEntityDaoConfig.getIdentityScope().clear();
        rankEntityDaoConfig.getIdentityScope().clear();
        rankPermissionEntityDaoConfig.getIdentityScope().clear();
        roomEntityDaoConfig.getIdentityScope().clear();
        scheduleEntityDaoConfig.getIdentityScope().clear();
        sellCheckEntityDaoConfig.getIdentityScope().clear();
        tableEntityDaoConfig.getIdentityScope().clear();
        taocanEntityDaoConfig.getIdentityScope().clear();
        taocanGroupDishEntityDaoConfig.getIdentityScope().clear();
        taocanGroupEntityDaoConfig.getIdentityScope().clear();
        taocanTypeEntityDaoConfig.getIdentityScope().clear();
        specifyEntityDaoConfig.getIdentityScope().clear();
        dishSpecifyEntityDaoConfig.getIdentityScope().clear();
        takeOutOrderEntityDaoConfig.getIdentityScope().clear();
        cashierDisplayEntityDaoConfig.getIdentityScope().clear();
        specialEntityDaoConfig.getIdentityScope().clear();
        mantissaEntityDaoConfig.getIdentityScope().clear();
        suplusEntityDaoConfig.getIdentityScope().clear();
        grouponEntityDaoConfig.getIdentityScope().clear();
        grouponTaocanEntityDaoConfig.getIdentityScope().clear();
        discountEntityDaoConfig.getIdentityScope().clear();
        dishTypeDiscountEntityDaoConfig.getIdentityScope().clear();
        printCashierEntityDaoConfig.getIdentityScope().clear();
        cashierClassifyEntityDaoConfig.getIdentityScope().clear();
        cashierDishEntityDaoConfig.getIdentityScope().clear();
        printKitchenEntityDaoConfig.getIdentityScope().clear();
        printKitchenClassifyEntityDaoConfig.getIdentityScope().clear();
        printKitchenDishEntityDaoConfig.getIdentityScope().clear();
        standbyPrinterEntityDaoConfig.getIdentityScope().clear();
        printRemarkEntityDaoConfig.getIdentityScope().clear();
        basicsPartnerEntityDaoConfig.getIdentityScope().clear();
        shopMealsEntityDaoConfig.getIdentityScope().clear();
        shopPaymentEntityDaoConfig.getIdentityScope().clear();
        shopReceivableEntityDaoConfig.getIdentityScope().clear();
        shopTimeEntityDaoConfig.getIdentityScope().clear();
        systemMessageEntityDaoConfig.getIdentityScope().clear();
        wXMessageEntityDaoConfig.getIdentityScope().clear();
        storeMessageEntityDaoConfig.getIdentityScope().clear();
        discountHistoryEntityDaoConfig.getIdentityScope().clear();
        someDiscountGoodsEntityDaoConfig.getIdentityScope().clear();
        orderTaocanGroupDishEntityDaoConfig.getIdentityScope().clear();
        printerFailedHistoryEntityDaoConfig.getIdentityScope().clear();
        jpushMessageEntityDaoConfig.getIdentityScope().clear();
        billAccountEntityDaoConfig.getIdentityScope().clear();
        billAccountPersonEntityDaoConfig.getIdentityScope().clear();
        billAccountSignEntityDaoConfig.getIdentityScope().clear();
        billAccountHistoryEntityDaoConfig.getIdentityScope().clear();
        uploadDataEntityDaoConfig.getIdentityScope().clear();
        vipCardEntityDaoConfig.getIdentityScope().clear();
        wxOrderMessageEntityDaoConfig.getIdentityScope().clear();
        printResultEntityDaoConfig.getIdentityScope().clear();
        turnoverHistoryEntityDaoConfig.getIdentityScope().clear();
        tableCodeEntityDaoConfig.getIdentityScope().clear();
        sendPersonEntityDaoConfig.getIdentityScope().clear();
        materialEntityDaoConfig.getIdentityScope().clear();
        dishTypeMaterialEntityDaoConfig.getIdentityScope().clear();
        dishSelectedMaterialEntityDaoConfig.getIdentityScope().clear();
    }

    public AreaEntityDao getAreaEntityDao() {
        return areaEntityDao;
    }

    public ArrangeEntityDao getArrangeEntityDao() {
        return arrangeEntityDao;
    }

    public DishEntityDao getDishEntityDao() {
        return dishEntityDao;
    }

    public DishTypeEntityDao getDishTypeEntityDao() {
        return dishTypeEntityDao;
    }

    public EmployeeEntityDao getEmployeeEntityDao() {
        return employeeEntityDao;
    }

    public KichenDishEntityDao getKichenDishEntityDao() {
        return kichenDishEntityDao;
    }

    public KichenPrintEntityDao getKichenPrintEntityDao() {
        return kichenPrintEntityDao;
    }

    public KitchenDishTypeEntityDao getKitchenDishTypeEntityDao() {
        return kitchenDishTypeEntityDao;
    }

    public KitchenDisPrintEntityDao getKitchenDisPrintEntityDao() {
        return kitchenDisPrintEntityDao;
    }

    public OrderDishEntityDao getOrderDishEntityDao() {
        return orderDishEntityDao;
    }

    public OrderEntityDao getOrderEntityDao() {
        return orderEntityDao;
    }

    public PayModeEntityDao getPayModeEntityDao() {
        return payModeEntityDao;
    }

    public PermissionEntityDao getPermissionEntityDao() {
        return permissionEntityDao;
    }

    public PracticeEntityDao getPracticeEntityDao() {
        return practiceEntityDao;
    }

    public DishPracticeEntityDao getDishPracticeEntityDao() {
        return dishPracticeEntityDao;
    }

    public RankEntityDao getRankEntityDao() {
        return rankEntityDao;
    }

    public RankPermissionEntityDao getRankPermissionEntityDao() {
        return rankPermissionEntityDao;
    }

    public RoomEntityDao getRoomEntityDao() {
        return roomEntityDao;
    }

    public ScheduleEntityDao getScheduleEntityDao() {
        return scheduleEntityDao;
    }

    public SellCheckEntityDao getSellCheckEntityDao() {
        return sellCheckEntityDao;
    }

    public TableEntityDao getTableEntityDao() {
        return tableEntityDao;
    }

    public TaocanEntityDao getTaocanEntityDao() {
        return taocanEntityDao;
    }

    public TaocanGroupDishEntityDao getTaocanGroupDishEntityDao() {
        return taocanGroupDishEntityDao;
    }

    public TaocanGroupEntityDao getTaocanGroupEntityDao() {
        return taocanGroupEntityDao;
    }

    public TaocanTypeEntityDao getTaocanTypeEntityDao() {
        return taocanTypeEntityDao;
    }

    public SpecifyEntityDao getSpecifyEntityDao() {
        return specifyEntityDao;
    }

    public DishSpecifyEntityDao getDishSpecifyEntityDao() {
        return dishSpecifyEntityDao;
    }

    public TakeOutOrderEntityDao getTakeOutOrderEntityDao() {
        return takeOutOrderEntityDao;
    }

    public CashierDisplayEntityDao getCashierDisplayEntityDao() {
        return cashierDisplayEntityDao;
    }

    public SpecialEntityDao getSpecialEntityDao() {
        return specialEntityDao;
    }

    public MantissaEntityDao getMantissaEntityDao() {
        return mantissaEntityDao;
    }

    public SuplusEntityDao getSuplusEntityDao() {
        return suplusEntityDao;
    }

    public GrouponEntityDao getGrouponEntityDao() {
        return grouponEntityDao;
    }

    public GrouponTaocanEntityDao getGrouponTaocanEntityDao() {
        return grouponTaocanEntityDao;
    }

    public DiscountEntityDao getDiscountEntityDao() {
        return discountEntityDao;
    }

    public DishTypeDiscountEntityDao getDishTypeDiscountEntityDao() {
        return dishTypeDiscountEntityDao;
    }

    public PrintCashierEntityDao getPrintCashierEntityDao() {
        return printCashierEntityDao;
    }

    public CashierClassifyEntityDao getCashierClassifyEntityDao() {
        return cashierClassifyEntityDao;
    }

    public CashierDishEntityDao getCashierDishEntityDao() {
        return cashierDishEntityDao;
    }

    public PrintKitchenEntityDao getPrintKitchenEntityDao() {
        return printKitchenEntityDao;
    }

    public PrintKitchenClassifyEntityDao getPrintKitchenClassifyEntityDao() {
        return printKitchenClassifyEntityDao;
    }

    public PrintKitchenDishEntityDao getPrintKitchenDishEntityDao() {
        return printKitchenDishEntityDao;
    }

    public StandbyPrinterEntityDao getStandbyPrinterEntityDao() {
        return standbyPrinterEntityDao;
    }

    public PrintRemarkEntityDao getPrintRemarkEntityDao() {
        return printRemarkEntityDao;
    }

    public BasicsPartnerEntityDao getBasicsPartnerEntityDao() {
        return basicsPartnerEntityDao;
    }

    public ShopMealsEntityDao getShopMealsEntityDao() {
        return shopMealsEntityDao;
    }

    public ShopPaymentEntityDao getShopPaymentEntityDao() {
        return shopPaymentEntityDao;
    }

    public ShopReceivableEntityDao getShopReceivableEntityDao() {
        return shopReceivableEntityDao;
    }

    public ShopTimeEntityDao getShopTimeEntityDao() {
        return shopTimeEntityDao;
    }

    public SystemMessageEntityDao getSystemMessageEntityDao() {
        return systemMessageEntityDao;
    }

    public WXMessageEntityDao getWXMessageEntityDao() {
        return wXMessageEntityDao;
    }

    public StoreMessageEntityDao getStoreMessageEntityDao() {
        return storeMessageEntityDao;
    }

    public DiscountHistoryEntityDao getDiscountHistoryEntityDao() {
        return discountHistoryEntityDao;
    }

    public SomeDiscountGoodsEntityDao getSomeDiscountGoodsEntityDao() {
        return someDiscountGoodsEntityDao;
    }

    public OrderTaocanGroupDishEntityDao getOrderTaocanGroupDishEntityDao() {
        return orderTaocanGroupDishEntityDao;
    }

    public PrinterFailedHistoryEntityDao getPrinterFailedHistoryEntityDao() {
        return printerFailedHistoryEntityDao;
    }

    public JpushMessageEntityDao getJpushMessageEntityDao() {
        return jpushMessageEntityDao;
    }

    public BillAccountEntityDao getBillAccountEntityDao() {
        return billAccountEntityDao;
    }

    public BillAccountPersonEntityDao getBillAccountPersonEntityDao() {
        return billAccountPersonEntityDao;
    }

    public BillAccountSignEntityDao getBillAccountSignEntityDao() {
        return billAccountSignEntityDao;
    }

    public BillAccountHistoryEntityDao getBillAccountHistoryEntityDao() {
        return billAccountHistoryEntityDao;
    }

    public UploadDataEntityDao getUploadDataEntityDao() {
        return uploadDataEntityDao;
    }

    public VipCardEntityDao getVipCardEntityDao() {
        return vipCardEntityDao;
    }

    public WxOrderMessageEntityDao getWxOrderMessageEntityDao() {
        return wxOrderMessageEntityDao;
    }

    public PrintResultEntityDao getPrintResultEntityDao() {
        return printResultEntityDao;
    }

    public TurnoverHistoryEntityDao getTurnoverHistoryEntityDao() {
        return turnoverHistoryEntityDao;
    }

    public TableCodeEntityDao getTableCodeEntityDao() {
        return tableCodeEntityDao;
    }

    public SendPersonEntityDao getSendPersonEntityDao() {
        return sendPersonEntityDao;
    }

    public MaterialEntityDao getMaterialEntityDao() {
        return materialEntityDao;
    }

    public DishTypeMaterialEntityDao getDishTypeMaterialEntityDao() {
        return dishTypeMaterialEntityDao;
    }

    public DishSelectedMaterialEntityDao getDishSelectedMaterialEntityDao() {
        return dishSelectedMaterialEntityDao;
    }

}
