package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "DISCOUNT_HISTORY_ENTITY".
 */
public class DiscountHistoryEntity implements Parcelable {

    private Long id;
    /** Not-null value. */
    private String discountHistoryId;
    private String orderId;
    private Integer discountType;
    private Integer discountRate;
    private String discountReason;
    private String discountId;
    private Long createTime;
    private Integer isAbleDiscount;

    public DiscountHistoryEntity() {
    }

    public DiscountHistoryEntity(Long id) {
        this.id = id;
    }

    public DiscountHistoryEntity(Long id, String discountHistoryId, String orderId, Integer discountType, Integer discountRate, String discountReason, String discountId, Long createTime, Integer isAbleDiscount) {
        this.id = id;
        this.discountHistoryId = discountHistoryId;
        this.orderId = orderId;
        this.discountType = discountType;
        this.discountRate = discountRate;
        this.discountReason = discountReason;
        this.discountId = discountId;
        this.createTime = createTime;
        this.isAbleDiscount = isAbleDiscount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDiscountHistoryId() {
        return discountHistoryId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDiscountHistoryId(String discountHistoryId) {
        this.discountHistoryId = discountHistoryId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public Integer getDiscountType() {
        return discountType;
    }

    public void setDiscountType(Integer discountType) {
        this.discountType = discountType;
    }

    public Integer getDiscountRate() {
        return discountRate;
    }

    public void setDiscountRate(Integer discountRate) {
        this.discountRate = discountRate;
    }

    public String getDiscountReason() {
        return discountReason;
    }

    public void setDiscountReason(String discountReason) {
        this.discountReason = discountReason;
    }

    public String getDiscountId() {
        return discountId;
    }

    public void setDiscountId(String discountId) {
        this.discountId = discountId;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Integer getIsAbleDiscount() {
        return isAbleDiscount;
    }

    public void setIsAbleDiscount(Integer isAbleDiscount) {
        this.isAbleDiscount = isAbleDiscount;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.discountHistoryId);
        dest.writeString(this.orderId);
        dest.writeValue(this.discountType);
        dest.writeValue(this.discountRate);
        dest.writeString(this.discountReason);
        dest.writeString(this.discountId);
        dest.writeValue(this.createTime);
        dest.writeValue(this.isAbleDiscount);
    }

    protected DiscountHistoryEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.discountHistoryId = in.readString();
        this.orderId = in.readString();
        this.discountType = (Integer) in.readValue(Integer.class.getClassLoader());
        this.discountRate = (Integer) in.readValue(Integer.class.getClassLoader());
        this.discountReason = in.readString();
        this.discountId = in.readString();
        this.createTime = (Long) in.readValue(Long.class.getClassLoader());
        this.isAbleDiscount = (Integer) in.readValue(Integer.class.getClassLoader());
    }

    public static final Parcelable.Creator<DiscountHistoryEntity> CREATOR = new Parcelable.Creator<DiscountHistoryEntity>() {
        @Override
        public DiscountHistoryEntity createFromParcel(Parcel source) {
            return new DiscountHistoryEntity(source);
        }

        @Override
        public DiscountHistoryEntity[] newArray(int size) {
            return new DiscountHistoryEntity[size];
        }
    };
}
