package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.GoodsTypePercentageVo;

/**
 * Entity mapped to table "DISH_TYPE_DISCOUNT_ENTITY".
 */
public class DishTypeDiscountEntity {

    private Long id;
    /** Not-null value. */
    private String dishTypeDiscountId;
    private String discountId;
    private String dishTypeId;
    private Integer dishTypePercentage;

    public DishTypeDiscountEntity() {
    }

    public DishTypeDiscountEntity(Long id) {
        this.id = id;
    }

    public DishTypeDiscountEntity(Long id, String dishTypeDiscountId, String discountId, String dishTypeId, Integer dishTypePercentage) {
        this.id = id;
        this.dishTypeDiscountId = dishTypeDiscountId;
        this.discountId = discountId;
        this.dishTypeId = dishTypeId;
        this.dishTypePercentage = dishTypePercentage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDishTypeDiscountId() {
        return dishTypeDiscountId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDishTypeDiscountId(String dishTypeDiscountId) {
        this.dishTypeDiscountId = dishTypeDiscountId;
    }

    public String getDiscountId() {
        return discountId;
    }

    public void setDiscountId(String discountId) {
        this.discountId = discountId;
    }

    public String getDishTypeId() {
        return dishTypeId;
    }

    public void setDishTypeId(String dishTypeId) {
        this.dishTypeId = dishTypeId;
    }

    public Integer getDishTypePercentage() {
        return dishTypePercentage;
    }

    public void setDishTypePercentage(Integer dishTypePercentage) {
        this.dishTypePercentage = dishTypePercentage;
    }

    public DishTypeDiscountEntity(GoodsTypePercentageVo goodsTypePercentageModel){
        this.dishTypeDiscountId = goodsTypePercentageModel.getId();
        this.discountId = goodsTypePercentageModel.getDiscountId();
        this.dishTypeId = goodsTypePercentageModel.getGoodsTypeId();
        this.dishTypePercentage = goodsTypePercentageModel.getDiscount();
    }

    public static ResultObjectBuilder<DishTypeDiscountEntity> builder = new ResultObjectBuilder<DishTypeDiscountEntity>() {
        @Override
        public DishTypeDiscountEntity build(ResultSet rs) throws SQLException {
            DishTypeDiscountEntity dishTypeDiscountEntity = new DishTypeDiscountEntity();
            dishTypeDiscountEntity.setDishTypeDiscountId(rs.getString("c_id"));
            dishTypeDiscountEntity.setDiscountId(rs.getString("c_discount_id"));
            dishTypeDiscountEntity.setDishTypeId(rs.getString("c_goods_type"));
            dishTypeDiscountEntity.setDishTypePercentage(rs.getInt("c_discount"));
            return dishTypeDiscountEntity;
        }
    };
}
