package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.GoodsHasMakeVo;

/**
 * Entity mapped to table "DISH_PRACTICE_ENTITY".
 */
public class DishPracticeEntity {

    private Long id;
    /** Not-null value. */
    private String dishPracticeId;
    private String practiceId;
    private String dishId;
    private Integer increaseMode;
    private Float increaseValue;

    public DishPracticeEntity() {
    }

    public DishPracticeEntity(Long id) {
        this.id = id;
    }

    public DishPracticeEntity(Long id, String dishPracticeId, String practiceId, String dishId, Integer increaseMode, Float increaseValue) {
        this.id = id;
        this.dishPracticeId = dishPracticeId;
        this.practiceId = practiceId;
        this.dishId = dishId;
        this.increaseMode = increaseMode;
        this.increaseValue = increaseValue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDishPracticeId() {
        return dishPracticeId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDishPracticeId(String dishPracticeId) {
        this.dishPracticeId = dishPracticeId;
    }

    public String getPracticeId() {
        return practiceId;
    }

    public void setPracticeId(String practiceId) {
        this.practiceId = practiceId;
    }

    public String getDishId() {
        return dishId;
    }

    public void setDishId(String dishId) {
        this.dishId = dishId;
    }

    public Integer getIncreaseMode() {
        return increaseMode;
    }

    public void setIncreaseMode(Integer increaseMode) {
        this.increaseMode = increaseMode;
    }

    public Float getIncreaseValue() {
        return increaseValue;
    }

    public void setIncreaseValue(Float increaseValue) {
        this.increaseValue = increaseValue;
    }

    public DishPracticeEntity(GoodsHasMakeVo goodsHasMake){
        this.dishPracticeId = goodsHasMake.getId();
        this.practiceId = goodsHasMake.getMakeId();
        this.dishId = goodsHasMake.getGoodsId();
        this.increaseMode = goodsHasMake.getAddPriceType();
        this.increaseValue = ((float)goodsHasMake.getMakeAddPrice())/100;
        Log.d("###", "菜品做法: "+this.toString());
    }

    @Override
    public String toString() {
        return "DishPracticeEntity{" +
                "id=" + id +
                ", dishPracticeId='" + dishPracticeId + '\'' +
                ", practiceId='" + practiceId + '\'' +
                ", dishId='" + dishId + '\'' +
                ", increaseMode=" + increaseMode +
                ", increaseValue=" + increaseValue +
                '}';
    }

    public static ResultObjectBuilder<DishPracticeEntity> builder = new ResultObjectBuilder<DishPracticeEntity>() {
        @Override
        public DishPracticeEntity build(ResultSet rs) throws SQLException {
            DishPracticeEntity dishPracticeEntity = new DishPracticeEntity();
            dishPracticeEntity.setDishPracticeId(rs.getString("c_id"));
            dishPracticeEntity.setPracticeId(rs.getString("c_make"));
            dishPracticeEntity.setDishId(rs.getString("c_goods"));
            dishPracticeEntity.setIncreaseMode(rs.getInt("c_add_price_type"));
            dishPracticeEntity.setIncreaseValue((float) rs.getInt("c_make_add_price")/100);
            return dishPracticeEntity;
        }
    };

}
