package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.GoodsHasGuigeVo;

/**
 * Entity mapped to table "DISH_SPECIFY_ENTITY".
 */
public class DishSpecifyEntity {

    private Long id;
    /** Not-null value. */
    private String dishSpecifyId;
    private String dishId;
    private String specifyId;
    private Float defaultPrice;
    private Float customPrice;

    public DishSpecifyEntity() {
    }

    public DishSpecifyEntity(Long id) {
        this.id = id;
    }

    public DishSpecifyEntity(Long id, String dishSpecifyId, String dishId, String specifyId, Float defaultPrice, Float customPrice) {
        this.id = id;
        this.dishSpecifyId = dishSpecifyId;
        this.dishId = dishId;
        this.specifyId = specifyId;
        this.defaultPrice = defaultPrice;
        this.customPrice = customPrice;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDishSpecifyId() {
        return dishSpecifyId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDishSpecifyId(String dishSpecifyId) {
        this.dishSpecifyId = dishSpecifyId;
    }

    public String getDishId() {
        return dishId;
    }

    public void setDishId(String dishId) {
        this.dishId = dishId;
    }

    public String getSpecifyId() {
        return specifyId;
    }

    public void setSpecifyId(String specifyId) {
        this.specifyId = specifyId;
    }

    public Float getDefaultPrice() {
        return defaultPrice;
    }

    public void setDefaultPrice(Float defaultPrice) {
        this.defaultPrice = defaultPrice;
    }

    public Float getCustomPrice() {
        return customPrice;
    }

    public void setCustomPrice(Float customPrice) {
        this.customPrice = customPrice;
    }

    public DishSpecifyEntity(GoodsHasGuigeVo goodsHasGuige){
        this.dishSpecifyId = goodsHasGuige.getId();
        this.specifyId = goodsHasGuige.getGuigeId();
        this.dishId = goodsHasGuige.getGoodsId();
        this.defaultPrice = ((float)goodsHasGuige.getDefaultPrice())/100;
        this.customPrice = ((float)goodsHasGuige.getCustomPrice())/100;
    }

    public static ResultObjectBuilder<DishSpecifyEntity> builder = new ResultObjectBuilder<DishSpecifyEntity>() {
        @Override
        public DishSpecifyEntity build(ResultSet rs) throws SQLException {
            DishSpecifyEntity dishSpecifyEntity = new DishSpecifyEntity();
            dishSpecifyEntity.setDishSpecifyId(rs.getString("c_id"));
            dishSpecifyEntity.setSpecifyId(rs.getString("c_guige"));
            dishSpecifyEntity.setDishId(rs.getString("c_goods"));
            dishSpecifyEntity.setDefaultPrice((float) rs.getInt("c_default_price")/100);
            dishSpecifyEntity.setCustomPrice((float) rs.getInt("c_custom_price")/100);
            return dishSpecifyEntity;
        }
    };

}
