package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DISH_SELECTED_MATERIAL_ENTITY".
 */
public class DishSelectedMaterialEntity {
    private Long id;
    private String dishSelectedMaterialId;//选择菜品物料生成的记录ID
    private String orderId;//订单ID
    private String orderDishId;//选择菜品的记录ID
    private String dishTypeMaterialId;//菜品分类对应物料的记录ID
    private String materialId;//物料ID
    private String materialName;//物料名称
    private Integer materialPrice;//物料单价
    private Integer selectedCount;//物料的数量
    private Integer totalPrice;//物料总价

    public DishSelectedMaterialEntity() {
    }

    public DishSelectedMaterialEntity(Long id) {
        this.id = id;
    }

    public DishSelectedMaterialEntity(Long id, String dishSelectedMaterialId, String orderId, String orderDishId, String dishTypeMaterialId, String materialId, String materialName, Integer materialPrice, Integer selectedCount, Integer totalPrice) {
        this.id = id;
        this.dishSelectedMaterialId = dishSelectedMaterialId;
        this.orderId = orderId;
        this.orderDishId = orderDishId;
        this.dishTypeMaterialId = dishTypeMaterialId;
        this.materialId = materialId;
        this.materialName = materialName;
        this.materialPrice = materialPrice;
        this.selectedCount = selectedCount;
        this.totalPrice = totalPrice;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDishSelectedMaterialId() {
        return dishSelectedMaterialId;
    }

    public void setDishSelectedMaterialId(String dishSelectedMaterialId) {
        this.dishSelectedMaterialId = dishSelectedMaterialId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getOrderDishId() {
        return orderDishId;
    }

    public void setOrderDishId(String orderDishId) {
        this.orderDishId = orderDishId;
    }

    public String getDishTypeMaterialId() {
        return dishTypeMaterialId;
    }

    public void setDishTypeMaterialId(String dishTypeMaterialId) {
        this.dishTypeMaterialId = dishTypeMaterialId;
    }

    public String getMaterialId() {
        return materialId;
    }

    public void setMaterialId(String materialId) {
        this.materialId = materialId;
    }

    public String getMaterialName() {
        return materialName;
    }

    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }

    public Integer getMaterialPrice() {
        return materialPrice;
    }

    public void setMaterialPrice(Integer materialPrice) {
        this.materialPrice = materialPrice;
    }

    public Integer getSelectedCount() {
        return selectedCount;
    }

    public void setSelectedCount(Integer selectedCount) {
        this.selectedCount = selectedCount;
    }

    public Integer getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }

}
