package jufeng.juyancash.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "DISH_TYPE_MATERIAL_ENTITY".
*/
public class DishTypeMaterialEntityDao extends AbstractDao<DishTypeMaterialEntity, Long> {

    public static final String TABLENAME = "DISH_TYPE_MATERIAL_ENTITY";

    /**
     * Properties of entity DishTypeMaterialEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DishTypeMaterialId = new Property(1, String.class, "dishTypeMaterialId", false, "DISH_TYPE_MATERIAL_ID");
        public final static Property DishTypeId = new Property(2, String.class, "dishTypeId", false, "DISH_TYPE_ID");
        public final static Property MaterialId = new Property(3, String.class, "materialId", false, "MATERIAL_ID");
    };


    public DishTypeMaterialEntityDao(DaoConfig config) {
        super(config);
    }
    
    public DishTypeMaterialEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DISH_TYPE_MATERIAL_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"DISH_TYPE_MATERIAL_ID\" TEXT," + // 1: dishTypeMaterialId
                "\"DISH_TYPE_ID\" TEXT," + // 2: dishTypeId
                "\"MATERIAL_ID\" TEXT);"); // 3: materialId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DISH_TYPE_MATERIAL_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DishTypeMaterialEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String dishTypeMaterialId = entity.getDishTypeMaterialId();
        if (dishTypeMaterialId != null) {
            stmt.bindString(2, dishTypeMaterialId);
        }
 
        String dishTypeId = entity.getDishTypeId();
        if (dishTypeId != null) {
            stmt.bindString(3, dishTypeId);
        }
 
        String materialId = entity.getMaterialId();
        if (materialId != null) {
            stmt.bindString(4, materialId);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DishTypeMaterialEntity readEntity(Cursor cursor, int offset) {
        DishTypeMaterialEntity entity = new DishTypeMaterialEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // dishTypeMaterialId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // dishTypeId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // materialId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DishTypeMaterialEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDishTypeMaterialId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDishTypeId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMaterialId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DishTypeMaterialEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DishTypeMaterialEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
