package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.GrouponTaoCanVo;

/**
 * Entity mapped to table "GROUPON_TAOCAN_ENTITY".
 */
public class GrouponTaocanEntity implements Parcelable {

    private Long id;
    /** Not-null value. */
    private String grouponTaocanId;
    private String grouponId;
    private String grouponTaocanName;
    private Float grouponTaocanPrice;
    private Float grouponTaocanBalancePrice;
    private String grouponTaocanDesc;
    private Integer isAddToCashier;
    private Integer isOnline;

    public GrouponTaocanEntity() {
    }

    public GrouponTaocanEntity(Long id) {
        this.id = id;
    }

    public GrouponTaocanEntity(Long id, String grouponTaocanId, String grouponId, String grouponTaocanName, Float grouponTaocanPrice, Float grouponTaocanBalancePrice, String grouponTaocanDesc, Integer isAddToCashier, Integer isOnline) {
        this.id = id;
        this.grouponTaocanId = grouponTaocanId;
        this.grouponId = grouponId;
        this.grouponTaocanName = grouponTaocanName;
        this.grouponTaocanPrice = grouponTaocanPrice;
        this.grouponTaocanBalancePrice = grouponTaocanBalancePrice;
        this.grouponTaocanDesc = grouponTaocanDesc;
        this.isAddToCashier = isAddToCashier;
        this.isOnline = isOnline;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getGrouponTaocanId() {
        return grouponTaocanId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGrouponTaocanId(String grouponTaocanId) {
        this.grouponTaocanId = grouponTaocanId;
    }

    public String getGrouponId() {
        return grouponId;
    }

    public void setGrouponId(String grouponId) {
        this.grouponId = grouponId;
    }

    public String getGrouponTaocanName() {
        return grouponTaocanName;
    }

    public void setGrouponTaocanName(String grouponTaocanName) {
        this.grouponTaocanName = grouponTaocanName;
    }

    public Float getGrouponTaocanPrice() {
        return grouponTaocanPrice;
    }

    public void setGrouponTaocanPrice(Float grouponTaocanPrice) {
        this.grouponTaocanPrice = grouponTaocanPrice;
    }

    public Float getGrouponTaocanBalancePrice() {
        return grouponTaocanBalancePrice;
    }

    public void setGrouponTaocanBalancePrice(Float grouponTaocanBalancePrice) {
        this.grouponTaocanBalancePrice = grouponTaocanBalancePrice;
    }

    public String getGrouponTaocanDesc() {
        return grouponTaocanDesc;
    }

    public void setGrouponTaocanDesc(String grouponTaocanDesc) {
        this.grouponTaocanDesc = grouponTaocanDesc;
    }

    public Integer getIsAddToCashier() {
        return isAddToCashier;
    }

    public void setIsAddToCashier(Integer isAddToCashier) {
        this.isAddToCashier = isAddToCashier;
    }

    public Integer getIsOnline() {
        return isOnline;
    }

    public void setIsOnline(Integer isOnline) {
        this.isOnline = isOnline;
    }

    @Override
    public String toString() {
        return "GrouponTaocanEntity{" +
                "id=" + id +
                ", grouponTaocanId='" + grouponTaocanId + '\'' +
                ", grouponId='" + grouponId + '\'' +
                ", grouponTaocanName='" + grouponTaocanName + '\'' +
                ", grouponTaocanPrice=" + grouponTaocanPrice +
                ", grouponTaocanBalancePrice=" + grouponTaocanBalancePrice +
                ", grouponTaocanDesc='" + grouponTaocanDesc + '\'' +
                ", isAddToCashier=" + isAddToCashier +
                ", isOnline=" + isOnline +
                '}';
    }

    public GrouponTaocanEntity(GrouponTaoCanVo grouponTaoCanVo){
        this.grouponTaocanId = grouponTaoCanVo.getId();
        this.grouponId = grouponTaoCanVo.getGrouponId();
        this.grouponTaocanName = grouponTaoCanVo.getName();
        this.grouponTaocanPrice = ((float)grouponTaoCanVo.getPrice())/100;
        this.grouponTaocanBalancePrice = ((float)grouponTaoCanVo.getBalance())/100;
        this.isAddToCashier = grouponTaoCanVo.getCashier();
        this.isOnline = grouponTaoCanVo.getOnline();
    }

    public static ResultObjectBuilder<GrouponTaocanEntity> builder = new ResultObjectBuilder<GrouponTaocanEntity>() {
        @Override
        public GrouponTaocanEntity build(ResultSet rs) throws SQLException {
            GrouponTaocanEntity grouponTaocanEntity = new GrouponTaocanEntity();
            grouponTaocanEntity.setGrouponTaocanId(rs.getString("c_id"));
            grouponTaocanEntity.setGrouponId(rs.getString("c_groupon_id"));
            grouponTaocanEntity.setGrouponTaocanName(rs.getString("c_name"));
            grouponTaocanEntity.setGrouponTaocanPrice(rs.getFloat("c_price"));
            grouponTaocanEntity.setGrouponTaocanBalancePrice(rs.getFloat("c_balance"));
            grouponTaocanEntity.setIsAddToCashier(rs.getInt("c_cashier"));
            grouponTaocanEntity.setIsOnline(rs.getInt("c_online"));
            return grouponTaocanEntity;
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.grouponTaocanId);
        dest.writeString(this.grouponId);
        dest.writeString(this.grouponTaocanName);
        dest.writeValue(this.grouponTaocanPrice);
        dest.writeValue(this.grouponTaocanBalancePrice);
        dest.writeString(this.grouponTaocanDesc);
        dest.writeValue(this.isAddToCashier);
        dest.writeValue(this.isOnline);
    }

    protected GrouponTaocanEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.grouponTaocanId = in.readString();
        this.grouponId = in.readString();
        this.grouponTaocanName = in.readString();
        this.grouponTaocanPrice = (Float) in.readValue(Float.class.getClassLoader());
        this.grouponTaocanBalancePrice = (Float) in.readValue(Float.class.getClassLoader());
        this.grouponTaocanDesc = in.readString();
        this.isAddToCashier = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isOnline = (Integer) in.readValue(Integer.class.getClassLoader());
    }

    public static final Parcelable.Creator<GrouponTaocanEntity> CREATOR = new Parcelable.Creator<GrouponTaocanEntity>() {
        @Override
        public GrouponTaocanEntity createFromParcel(Parcel source) {
            return new GrouponTaocanEntity(source);
        }

        @Override
        public GrouponTaocanEntity[] newArray(int size) {
            return new GrouponTaocanEntity[size];
        }
    };
}
