package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "JPUSH_MESSAGE_ENTITY".
 */
public class JpushMessageEntity {

    private Long id;
    /** Not-null value. */
    private String jpushMessageId;
    private String message;
    private Integer type;
    private Long lastTime;
    private Integer count;

    public JpushMessageEntity() {
    }

    public JpushMessageEntity(Long id) {
        this.id = id;
    }

    public JpushMessageEntity(Long id, String jpushMessageId, String message, Integer type, Long lastTime, Integer count) {
        this.id = id;
        this.jpushMessageId = jpushMessageId;
        this.message = message;
        this.type = type;
        this.lastTime = lastTime;
        this.count = count;
    }

    @Override
    public String toString() {
        return "JpushMessageEntity{" +
                "id=" + id +
                ", jpushMessageId='" + jpushMessageId + '\'' +
                ", message='" + message + '\'' +
                ", type=" + type +
                ", lastTime=" + lastTime +
                ", count=" + count +
                '}';
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getJpushMessageId() {
        return jpushMessageId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJpushMessageId(String jpushMessageId) {
        this.jpushMessageId = jpushMessageId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getLastTime() {
        return lastTime;
    }

    public void setLastTime(Long lastTime) {
        this.lastTime = lastTime;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

}
