package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "KICHEN_PRINT_ENTITY".
 */
public class KichenPrintEntity {

    private Long id;
    /** Not-null value. */
    private String kichenId;
    private Integer printerType;
    private String printerName;
    private String printerIp;
    private Integer paperWidth;
    private Integer printChars;
    private Integer printNumber;
    private Integer isOneCut;
    private Integer isTotalCut;
    private Integer connectStatus;

    public KichenPrintEntity() {
    }

    public KichenPrintEntity(Long id) {
        this.id = id;
    }

    public KichenPrintEntity(Long id, String kichenId, Integer printerType, String printerName, String printerIp, Integer paperWidth, Integer printChars, Integer printNumber, Integer isOneCut, Integer isTotalCut, Integer connectStatus) {
        this.id = id;
        this.kichenId = kichenId;
        this.printerType = printerType;
        this.printerName = printerName;
        this.printerIp = printerIp;
        this.paperWidth = paperWidth;
        this.printChars = printChars;
        this.printNumber = printNumber;
        this.isOneCut = isOneCut;
        this.isTotalCut = isTotalCut;
        this.connectStatus = connectStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getKichenId() {
        return kichenId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKichenId(String kichenId) {
        this.kichenId = kichenId;
    }

    public Integer getPrinterType() {
        return printerType;
    }

    public void setPrinterType(Integer printerType) {
        this.printerType = printerType;
    }

    public String getPrinterName() {
        return printerName;
    }

    public void setPrinterName(String printerName) {
        this.printerName = printerName;
    }

    public String getPrinterIp() {
        return printerIp;
    }

    public void setPrinterIp(String printerIp) {
        this.printerIp = printerIp;
    }

    public Integer getPaperWidth() {
        return paperWidth;
    }

    public void setPaperWidth(Integer paperWidth) {
        this.paperWidth = paperWidth;
    }

    public Integer getPrintChars() {
        return printChars;
    }

    public void setPrintChars(Integer printChars) {
        this.printChars = printChars;
    }

    public Integer getPrintNumber() {
        return printNumber;
    }

    public void setPrintNumber(Integer printNumber) {
        this.printNumber = printNumber;
    }

    public Integer getIsOneCut() {
        return isOneCut;
    }

    public void setIsOneCut(Integer isOneCut) {
        this.isOneCut = isOneCut;
    }

    public Integer getIsTotalCut() {
        return isTotalCut;
    }

    public void setIsTotalCut(Integer isTotalCut) {
        this.isTotalCut = isTotalCut;
    }

    public Integer getConnectStatus() {
        return connectStatus;
    }

    public void setConnectStatus(Integer connectStatus) {
        this.connectStatus = connectStatus;
    }

}
