package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "KICHEN_DISH_ENTITY".
 */
public class KichenDishEntity {

    private Long id;
    private String dishId;
    private String kichenId;

    public KichenDishEntity() {
    }

    public KichenDishEntity(Long id) {
        this.id = id;
    }

    public KichenDishEntity(Long id, String dishId, String kichenId) {
        this.id = id;
        this.dishId = dishId;
        this.kichenId = kichenId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDishId() {
        return dishId;
    }

    public void setDishId(String dishId) {
        this.dishId = dishId;
    }

    public String getKichenId() {
        return kichenId;
    }

    public void setKichenId(String kichenId) {
        this.kichenId = kichenId;
    }

}
