package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "KITCHEN_DISH_TYPE_ENTITY".
 */
public class KitchenDishTypeEntity {

    private Long id;
    private String dishTypeId;
    private String kichenId;

    public KitchenDishTypeEntity() {
    }

    public KitchenDishTypeEntity(Long id) {
        this.id = id;
    }

    public KitchenDishTypeEntity(Long id, String dishTypeId, String kichenId) {
        this.id = id;
        this.dishTypeId = dishTypeId;
        this.kichenId = kichenId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDishTypeId() {
        return dishTypeId;
    }

    public void setDishTypeId(String dishTypeId) {
        this.dishTypeId = dishTypeId;
    }

    public String getKichenId() {
        return kichenId;
    }

    public void setKichenId(String kichenId) {
        this.kichenId = kichenId;
    }

}
