package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.MantissaVo;

/**
 * Entity mapped to table "MANTISSA_ENTITY".
 */
public class MantissaEntity {

    private Long id;
    /** Not-null value. */
    private String mantissaId;
    private Integer mantissaValue;
    private Integer reduceValue;

    public MantissaEntity() {
    }

    public MantissaEntity(Long id) {
        this.id = id;
    }

    public MantissaEntity(Long id, String mantissaId, Integer mantissaValue, Integer reduceValue) {
        this.id = id;
        this.mantissaId = mantissaId;
        this.mantissaValue = mantissaValue;
        this.reduceValue = reduceValue;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMantissaId() {
        return mantissaId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMantissaId(String mantissaId) {
        this.mantissaId = mantissaId;
    }

    public Integer getMantissaValue() {
        return mantissaValue;
    }

    public void setMantissaValue(Integer mantissaValue) {
        this.mantissaValue = mantissaValue;
    }

    public Integer getReduceValue() {
        return reduceValue;
    }

    public void setReduceValue(Integer reduceValue) {
        this.reduceValue = reduceValue;
    }

    public MantissaEntity(MantissaVo mantissa){
        this.mantissaId = mantissa.getId();
        this.mantissaValue = mantissa.getMantissa();
        this.reduceValue = mantissa.getReduce();
    }

    public static ResultObjectBuilder<MantissaEntity> builder = new ResultObjectBuilder<MantissaEntity>() {
        @Override
        public MantissaEntity build(ResultSet rs) throws SQLException {
            MantissaEntity mantissaEntity = new MantissaEntity();
            mantissaEntity.setMantissaId(rs.getString("c_id"));
            mantissaEntity.setMantissaValue(rs.getInt("c_mantissa"));
            mantissaEntity.setReduceValue(rs.getInt("c_reduce"));
            return mantissaEntity;
        }
    };

}
