package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import jufeng.juyancash.syncdata.GoodsMaterialModel;

/**
 * Entity mapped to table "MATERIAL_ENTITY".
 */
public class MaterialEntity {

    private Long id;
    private String materialId;
    private String materialName;
    private Integer materialPrice;

    public MaterialEntity() {
    }

    public MaterialEntity(Long id) {
        this.id = id;
    }

    public MaterialEntity(Long id, String materialId, String materialName, Integer materialPrice) {
        this.id = id;
        this.materialId = materialId;
        this.materialName = materialName;
        this.materialPrice = materialPrice;
    }

    public MaterialEntity(GoodsMaterialModel vo){
        this.materialId = vo.getId();
        this.materialName = vo.getName();
        this.materialPrice = vo.getPrice();
        Log.d("###", "原料："+this.toString());
    }

    @Override
    public String toString() {
        return "MaterialEntity{" +
                "id=" + id +
                ", materialId='" + materialId + '\'' +
                ", materialName='" + materialName + '\'' +
                ", materialPrice=" + materialPrice +
                '}';
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMaterialId() {
        return materialId;
    }

    public void setMaterialId(String materialId) {
        this.materialId = materialId;
    }

    public String getMaterialName() {
        return materialName;
    }

    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }

    public Integer getMaterialPrice() {
        return materialPrice;
    }

    public void setMaterialPrice(Integer materialPrice) {
        this.materialPrice = materialPrice;
    }

}
