package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

import jufeng.juyancash.util.CustomMethod;

/**
 * Entity mapped to table "ORDER_ENTITY".
 */
public class OrderEntity implements Parcelable {

    private Long id;
    /** Not-null value. */
    private String orderId;
    private String serialNumber;
    private Integer orderGuests;
    private Integer isLimited;
    private Integer limitedTime;
    private Integer remindTime;
    private Long openTime;
    private Long closeTime;
    private Integer closeMoney;
    private String tableId;
    private String areaId;
    private Integer orderStatus;
    private Integer orderNumber;
    private String cashierId;
    private String waiterId;
    private Integer treatmentMoney;
    private Integer selfTreatMoney;
    private Integer mantissaMoney;
    private Integer presentMoney;
    private Integer totalMoney;
    private Integer invoiceMoney;
    private Integer vipDiscountMoney;
    private Integer couponDiscountMoney;
    private Integer discountMoney;
    private Integer discountTotalMoney;
    private Integer isReturnOrder;
    private String returnOrderReason;
    private Integer isShift;
    private Integer orderType;
    private Integer isUpload;
    private Integer isJoinedTable;
    private Integer isJoinedOrder;
    private String joinedTableId;
    private String joinedOrderId;
    private Integer isVip;
    private String vipNo;
    private Integer vipType;
    private Integer vipBalance;
    private Integer isCoupon;
    private String userCouponId;
    private String couponId;
    private Integer couponType;
    private Integer couponFaceValue;
    private Integer couponCondition;
    private Integer isCouponWithVip;
    private Integer isCouponDiscountAll;
    private String couponVipno;
    private Integer isSync;
    private Integer storeVersion;
    private Integer dispacherType;
    private String dispacherName;
    private String dispacherTel;
    private String dispacherId;
    private Integer dispacherTc;
    private Integer dispacherExtralMoney;

    public OrderEntity() {
    }

    public OrderEntity(Long id) {
        this.id = id;
    }

    public OrderEntity(Long id, String orderId, String serialNumber, Integer orderGuests, Integer isLimited, Integer limitedTime, Integer remindTime, Long openTime, Long closeTime, Integer closeMoney, String tableId, String areaId, Integer orderStatus, Integer orderNumber, String cashierId, String waiterId, Integer treatmentMoney, Integer selfTreatMoney, Integer mantissaMoney, Integer presentMoney, Integer totalMoney, Integer invoiceMoney, Integer vipDiscountMoney, Integer couponDiscountMoney, Integer discountMoney, Integer discountTotalMoney, Integer isReturnOrder, String returnOrderReason, Integer isShift, Integer orderType, Integer isUpload, Integer isJoinedTable, Integer isJoinedOrder, String joinedTableId, String joinedOrderId, Integer isVip, String vipNo, Integer vipType, Integer vipBalance, Integer isCoupon, String userCouponId, String couponId, Integer couponType, Integer couponFaceValue, Integer couponCondition, Integer isCouponWithVip, Integer isCouponDiscountAll, String couponVipno, Integer isSync, Integer storeVersion, Integer dispacherType, String dispacherName, String dispacherTel, String dispacherId, Integer dispacherTc, Integer dispacherExtralMoney) {
        this.id = id;
        this.orderId = orderId;
        this.serialNumber = serialNumber;
        this.orderGuests = orderGuests;
        this.isLimited = isLimited;
        this.limitedTime = limitedTime;
        this.remindTime = remindTime;
        this.openTime = openTime;
        this.closeTime = closeTime;
        this.closeMoney = closeMoney;
        this.tableId = tableId;
        this.areaId = areaId;
        this.orderStatus = orderStatus;
        this.orderNumber = orderNumber;
        this.cashierId = cashierId;
        this.waiterId = waiterId;
        this.treatmentMoney = treatmentMoney;
        this.selfTreatMoney = selfTreatMoney;
        this.mantissaMoney = mantissaMoney;
        this.presentMoney = presentMoney;
        this.totalMoney = totalMoney;
        this.invoiceMoney = invoiceMoney;
        this.vipDiscountMoney = vipDiscountMoney;
        this.couponDiscountMoney = couponDiscountMoney;
        this.discountMoney = discountMoney;
        this.discountTotalMoney = discountTotalMoney;
        this.isReturnOrder = isReturnOrder;
        this.returnOrderReason = returnOrderReason;
        this.isShift = isShift;
        this.orderType = orderType;
        this.isUpload = isUpload;
        this.isJoinedTable = isJoinedTable;
        this.isJoinedOrder = isJoinedOrder;
        this.joinedTableId = joinedTableId;
        this.joinedOrderId = joinedOrderId;
        this.isVip = isVip;
        this.vipNo = vipNo;
        this.vipType = vipType;
        this.vipBalance = vipBalance;
        this.isCoupon = isCoupon;
        this.userCouponId = userCouponId;
        this.couponId = couponId;
        this.couponType = couponType;
        this.couponFaceValue = couponFaceValue;
        this.couponCondition = couponCondition;
        this.isCouponWithVip = isCouponWithVip;
        this.isCouponDiscountAll = isCouponDiscountAll;
        this.couponVipno = couponVipno;
        this.isSync = isSync;
        this.storeVersion = storeVersion;
        this.dispacherType = dispacherType;
        this.dispacherName = dispacherName;
        this.dispacherTel = dispacherTel;
        this.dispacherId = dispacherId;
        this.dispacherTc = dispacherTc;
        this.dispacherExtralMoney = dispacherExtralMoney;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOrderId() {
        return orderId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getSerialNumber() {
        return serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public Integer getOrderGuests() {
        return orderGuests;
    }

    public void setOrderGuests(Integer orderGuests) {
        this.orderGuests = orderGuests;
    }

    public Integer getIsLimited() {
        return isLimited;
    }

    public void setIsLimited(Integer isLimited) {
        this.isLimited = isLimited;
    }

    public Integer getLimitedTime() {
        return limitedTime;
    }

    public void setLimitedTime(Integer limitedTime) {
        this.limitedTime = limitedTime;
    }

    public Integer getRemindTime() {
        return remindTime;
    }

    public void setRemindTime(Integer remindTime) {
        this.remindTime = remindTime;
    }

    public Long getOpenTime() {
        return openTime;
    }

    public void setOpenTime(Long openTime) {
        this.openTime = openTime;
    }

    public Long getCloseTime() {
        return closeTime;
    }

    public void setCloseTime(Long closeTime) {
        this.closeTime = closeTime;
    }

    public Integer getCloseMoney() {
        return closeMoney;
    }

    public void setCloseMoney(Integer closeMoney) {
        this.closeMoney = closeMoney;
    }

    public String getTableId() {
        if(tableId == null){
            return "";
        }
        return tableId;
    }

    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

    public String getAreaId() {
        return areaId;
    }

    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    public Integer getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Integer getOrderNumber() {
        return orderNumber;
    }

    public String getOrderNumber1(){
        return CustomMethod.addZeroBefore(orderNumber);
    }

    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getCashierId() {
        return cashierId;
    }

    public void setCashierId(String cashierId) {
        this.cashierId = cashierId;
    }

    public String getWaiterId() {
        return waiterId;
    }

    public void setWaiterId(String waiterId) {
        this.waiterId = waiterId;
    }

    public Integer getTreatmentMoney() {
        return treatmentMoney;
    }

    public void setTreatmentMoney(Integer treatmentMoney) {
        this.treatmentMoney = treatmentMoney;
    }

    public Integer getSelfTreatMoney() {
        return selfTreatMoney;
    }

    public void setSelfTreatMoney(Integer selfTreatMoney) {
        this.selfTreatMoney = selfTreatMoney;
    }

    public Integer getMantissaMoney() {
        return mantissaMoney;
    }

    public void setMantissaMoney(Integer mantissaMoney) {
        this.mantissaMoney = mantissaMoney;
    }

    public Integer getPresentMoney() {
        return presentMoney;
    }

    public void setPresentMoney(Integer presentMoney) {
        this.presentMoney = presentMoney;
    }

    public Integer getTotalMoney() {
        return totalMoney;
    }

    public void setTotalMoney(Integer totalMoney) {
        this.totalMoney = totalMoney;
    }

    public Integer getInvoiceMoney() {
        return invoiceMoney;
    }

    public void setInvoiceMoney(Integer invoiceMoney) {
        this.invoiceMoney = invoiceMoney;
    }

    public Integer getVipDiscountMoney() {
        return vipDiscountMoney;
    }

    public void setVipDiscountMoney(Integer vipDiscountMoney) {
        this.vipDiscountMoney = vipDiscountMoney;
    }

    public Integer getCouponDiscountMoney() {
        return couponDiscountMoney;
    }

    public void setCouponDiscountMoney(Integer couponDiscountMoney) {
        this.couponDiscountMoney = couponDiscountMoney;
    }

    public Integer getDiscountMoney() {
        return discountMoney;
    }

    public void setDiscountMoney(Integer discountMoney) {
        this.discountMoney = discountMoney;
    }

    public Integer getDiscountTotalMoney() {
        return discountTotalMoney;
    }

    public void setDiscountTotalMoney(Integer discountTotalMoney) {
        this.discountTotalMoney = discountTotalMoney;
    }

    public Integer getIsReturnOrder() {
        return isReturnOrder;
    }

    public void setIsReturnOrder(Integer isReturnOrder) {
        this.isReturnOrder = isReturnOrder;
    }

    public String getReturnOrderReason() {
        return returnOrderReason;
    }

    public void setReturnOrderReason(String returnOrderReason) {
        this.returnOrderReason = returnOrderReason;
    }

    public Integer getIsShift() {
        return isShift;
    }

    public void setIsShift(Integer isShift) {
        this.isShift = isShift;
    }

    public Integer getOrderType() {
        return orderType;
    }

    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    public Integer getIsUpload() {
        return isUpload;
    }

    public void setIsUpload(Integer isUpload) {
        this.isUpload = isUpload;
    }

    public Integer getIsJoinedTable() {
        return isJoinedTable;
    }

    public void setIsJoinedTable(Integer isJoinedTable) {
        this.isJoinedTable = isJoinedTable;
    }

    public Integer getIsJoinedOrder() {
        return isJoinedOrder;
    }

    public void setIsJoinedOrder(Integer isJoinedOrder) {
        this.isJoinedOrder = isJoinedOrder;
    }

    public String getJoinedTableId() {
        return joinedTableId;
    }

    public void setJoinedTableId(String joinedTableId) {
        this.joinedTableId = joinedTableId;
    }

    public String getJoinedOrderId() {
        return joinedOrderId;
    }

    public void setJoinedOrderId(String joinedOrderId) {
        this.joinedOrderId = joinedOrderId;
    }

    public Integer getIsVip() {
        return isVip;
    }

    public void setIsVip(Integer isVip) {
        this.isVip = isVip;
    }

    public String getVipNo() {
        return vipNo;
    }

    public void setVipNo(String vipNo) {
        this.vipNo = vipNo;
    }

    public Integer getVipType() {
        return vipType;
    }

    public void setVipType(Integer vipType) {
        this.vipType = vipType;
    }

    public Integer getVipBalance() {
        return vipBalance;
    }

    public void setVipBalance(Integer vipBalance) {
        this.vipBalance = vipBalance;
    }

    public Integer getIsCoupon() {
        return isCoupon;
    }

    public void setIsCoupon(Integer isCoupon) {
        this.isCoupon = isCoupon;
    }

    public String getUserCouponId() {
        return userCouponId;
    }

    public void setUserCouponId(String userCouponId) {
        this.userCouponId = userCouponId;
    }

    public String getCouponId() {
        return couponId;
    }

    public void setCouponId(String couponId) {
        this.couponId = couponId;
    }

    public Integer getCouponType() {
        return couponType;
    }

    public void setCouponType(Integer couponType) {
        this.couponType = couponType;
    }

    public Integer getCouponFaceValue() {
        return couponFaceValue;
    }

    public void setCouponFaceValue(Integer couponFaceValue) {
        this.couponFaceValue = couponFaceValue;
    }

    public Integer getCouponCondition() {
        return couponCondition;
    }

    public void setCouponCondition(Integer couponCondition) {
        this.couponCondition = couponCondition;
    }

    public Integer getIsCouponWithVip() {
        return isCouponWithVip;
    }

    public void setIsCouponWithVip(Integer isCouponWithVip) {
        this.isCouponWithVip = isCouponWithVip;
    }

    public Integer getIsCouponDiscountAll() {
        return isCouponDiscountAll;
    }

    public void setIsCouponDiscountAll(Integer isCouponDiscountAll) {
        this.isCouponDiscountAll = isCouponDiscountAll;
    }

    public String getCouponVipno() {
        return couponVipno;
    }

    public void setCouponVipno(String couponVipno) {
        this.couponVipno = couponVipno;
    }

    public Integer getIsSync() {
        return isSync;
    }

    public void setIsSync(Integer isSync) {
        this.isSync = isSync;
    }

    public Integer getStoreVersion() {
        return storeVersion;
    }

    public void setStoreVersion(Integer storeVersion) {
        this.storeVersion = storeVersion;
    }

    public Integer getDispacherType() {
        return dispacherType;
    }

    public void setDispacherType(Integer dispacherType) {
        this.dispacherType = dispacherType;
    }

    public String getDispacherName() {
        return dispacherName;
    }

    public void setDispacherName(String dispacherName) {
        this.dispacherName = dispacherName;
    }

    public String getDispacherTel() {
        return dispacherTel;
    }

    public void setDispacherTel(String dispacherTel) {
        this.dispacherTel = dispacherTel;
    }

    public String getDispacherId() {
        return dispacherId;
    }

    public void setDispacherId(String dispacherId) {
        this.dispacherId = dispacherId;
    }

    public Integer getDispacherTc() {
        return dispacherTc;
    }

    public void setDispacherTc(Integer dispacherTc) {
        this.dispacherTc = dispacherTc;
    }

    public Integer getDispacherExtralMoney() {
        return dispacherExtralMoney;
    }

    public void setDispacherExtralMoney(Integer dispacherExtralMoney) {
        this.dispacherExtralMoney = dispacherExtralMoney;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.orderId);
        dest.writeString(this.serialNumber);
        dest.writeValue(this.orderGuests);
        dest.writeValue(this.isLimited);
        dest.writeValue(this.limitedTime);
        dest.writeValue(this.remindTime);
        dest.writeValue(this.openTime);
        dest.writeValue(this.closeTime);
        dest.writeValue(this.closeMoney);
        dest.writeString(this.tableId);
        dest.writeString(this.areaId);
        dest.writeValue(this.orderStatus);
        dest.writeValue(this.orderNumber);
        dest.writeString(this.cashierId);
        dest.writeString(this.waiterId);
        dest.writeValue(this.treatmentMoney);
        dest.writeValue(this.selfTreatMoney);
        dest.writeValue(this.mantissaMoney);
        dest.writeValue(this.presentMoney);
        dest.writeValue(this.totalMoney);
        dest.writeValue(this.invoiceMoney);
        dest.writeValue(this.vipDiscountMoney);
        dest.writeValue(this.couponDiscountMoney);
        dest.writeValue(this.discountMoney);
        dest.writeValue(this.discountTotalMoney);
        dest.writeValue(this.isReturnOrder);
        dest.writeString(this.returnOrderReason);
        dest.writeValue(this.isShift);
        dest.writeValue(this.orderType);
        dest.writeValue(this.isUpload);
        dest.writeValue(this.isJoinedTable);
        dest.writeValue(this.isJoinedOrder);
        dest.writeString(this.joinedTableId);
        dest.writeString(this.joinedOrderId);
        dest.writeValue(this.isVip);
        dest.writeString(this.vipNo);
        dest.writeValue(this.vipType);
        dest.writeValue(this.vipBalance);
        dest.writeValue(this.isCoupon);
        dest.writeString(this.userCouponId);
        dest.writeString(this.couponId);
        dest.writeValue(this.couponType);
        dest.writeValue(this.couponFaceValue);
        dest.writeValue(this.couponCondition);
        dest.writeValue(this.isCouponWithVip);
        dest.writeValue(this.isCouponDiscountAll);
        dest.writeString(this.couponVipno);
        dest.writeValue(this.isSync);
        dest.writeValue(this.storeVersion);
        dest.writeValue(this.dispacherType);
        dest.writeString(this.dispacherName);
        dest.writeString(this.dispacherTel);
        dest.writeString(this.dispacherId);
        dest.writeValue(this.dispacherTc);
        dest.writeValue(this.dispacherExtralMoney);
    }

    protected OrderEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.orderId = in.readString();
        this.serialNumber = in.readString();
        this.orderGuests = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isLimited = (Integer) in.readValue(Integer.class.getClassLoader());
        this.limitedTime = (Integer) in.readValue(Integer.class.getClassLoader());
        this.remindTime = (Integer) in.readValue(Integer.class.getClassLoader());
        this.openTime = (Long) in.readValue(Long.class.getClassLoader());
        this.closeTime = (Long) in.readValue(Long.class.getClassLoader());
        this.closeMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.tableId = in.readString();
        this.areaId = in.readString();
        this.orderStatus = (Integer) in.readValue(Integer.class.getClassLoader());
        this.orderNumber = (Integer) in.readValue(Integer.class.getClassLoader());
        this.cashierId = in.readString();
        this.waiterId = in.readString();
        this.treatmentMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.selfTreatMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.mantissaMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.presentMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.totalMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.invoiceMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.vipDiscountMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.couponDiscountMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.discountMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.discountTotalMoney = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isReturnOrder = (Integer) in.readValue(Integer.class.getClassLoader());
        this.returnOrderReason = in.readString();
        this.isShift = (Integer) in.readValue(Integer.class.getClassLoader());
        this.orderType = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isUpload = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isJoinedTable = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isJoinedOrder = (Integer) in.readValue(Integer.class.getClassLoader());
        this.joinedTableId = in.readString();
        this.joinedOrderId = in.readString();
        this.isVip = (Integer) in.readValue(Integer.class.getClassLoader());
        this.vipNo = in.readString();
        this.vipType = (Integer) in.readValue(Integer.class.getClassLoader());
        this.vipBalance = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isCoupon = (Integer) in.readValue(Integer.class.getClassLoader());
        this.userCouponId = in.readString();
        this.couponId = in.readString();
        this.couponType = (Integer) in.readValue(Integer.class.getClassLoader());
        this.couponFaceValue = (Integer) in.readValue(Integer.class.getClassLoader());
        this.couponCondition = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isCouponWithVip = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isCouponDiscountAll = (Integer) in.readValue(Integer.class.getClassLoader());
        this.couponVipno = in.readString();
        this.isSync = (Integer) in.readValue(Integer.class.getClassLoader());
        this.storeVersion = (Integer) in.readValue(Integer.class.getClassLoader());
        this.dispacherType = (Integer) in.readValue(Integer.class.getClassLoader());
        this.dispacherName = in.readString();
        this.dispacherTel = in.readString();
        this.dispacherId = in.readString();
        this.dispacherTc = (Integer) in.readValue(Integer.class.getClassLoader());
        this.dispacherExtralMoney = (Integer) in.readValue(Integer.class.getClassLoader());
    }

    public static final Parcelable.Creator<OrderEntity> CREATOR = new Parcelable.Creator<OrderEntity>() {
        @Override
        public OrderEntity createFromParcel(Parcel source) {
            return new OrderEntity(source);
        }

        @Override
        public OrderEntity[] newArray(int size) {
            return new OrderEntity[size];
        }
    };
}
