package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "PAY_MODE_ENTITY".
 */
public class PayModeEntity implements Parcelable {

    private Long id;
    /** Not-null value. */
    private String payModeId;
    private String orderId;
    private String paymentId;
    private String paymentName;
    private Integer paymentType;
    private Float payMoney;
    private Float payBalance;
    private Long payTime;
    private Integer isJoinOrderPay;
    private String electricOrderSerial;

    public PayModeEntity() {
    }

    public PayModeEntity(Long id) {
        this.id = id;
    }

    public PayModeEntity(Long id, String payModeId, String orderId, String paymentId, String paymentName, Integer paymentType, Float payMoney, Float payBalance, Long payTime, Integer isJoinOrderPay, String electricOrderSerial) {
        this.id = id;
        this.payModeId = payModeId;
        this.orderId = orderId;
        this.paymentId = paymentId;
        this.paymentName = paymentName;
        this.paymentType = paymentType;
        this.payMoney = payMoney;
        this.payBalance = payBalance;
        this.payTime = payTime;
        this.isJoinOrderPay = isJoinOrderPay;
        this.electricOrderSerial = electricOrderSerial;
    }

    public PayModeEntity(PayModeEntity payModeEntity){
        this.id = payModeEntity.getId();
        this.payModeId = payModeEntity.getPayModeId();
        this.orderId = payModeEntity.getOrderId();
        this.paymentId = payModeEntity.getPaymentId();
        this.paymentName = payModeEntity.getPaymentName();
        this.paymentType = payModeEntity.getPaymentType();
        this.payMoney = payModeEntity.getPayMoney();
        this.payBalance = payModeEntity.getPayBalance();
        this.payTime = payModeEntity.getPayTime();
        this.isJoinOrderPay = payModeEntity.getIsJoinOrderPay();
        this.electricOrderSerial = payModeEntity.getElectricOrderSerial();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPayModeId() {
        return payModeId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPayModeId(String payModeId) {
        this.payModeId = payModeId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    public String getPaymentName() {
        return paymentName;
    }

    public void setPaymentName(String paymentName) {
        this.paymentName = paymentName;
    }

    public Integer getPaymentType() {
        return paymentType;
    }

    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    public Float getPayMoney() {
        return payMoney;
    }

    public void setPayMoney(Float payMoney) {
        this.payMoney = payMoney;
    }

    public Float getPayBalance() {
        return payBalance;
    }

    public void setPayBalance(Float payBalance) {
        this.payBalance = payBalance;
    }

    public Long getPayTime() {
        return payTime;
    }

    public void setPayTime(Long payTime) {
        this.payTime = payTime;
    }

    public Integer getIsJoinOrderPay() {
        return isJoinOrderPay;
    }

    public void setIsJoinOrderPay(Integer isJoinOrderPay) {
        this.isJoinOrderPay = isJoinOrderPay;
    }

    public String getElectricOrderSerial() {
        return electricOrderSerial;
    }

    public void setElectricOrderSerial(String electricOrderSerial) {
        this.electricOrderSerial = electricOrderSerial;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.payModeId);
        dest.writeString(this.orderId);
        dest.writeString(this.paymentId);
        dest.writeString(this.paymentName);
        dest.writeValue(this.paymentType);
        dest.writeValue(this.payMoney);
        dest.writeValue(this.payBalance);
        dest.writeValue(this.payTime);
        dest.writeValue(this.isJoinOrderPay);
        dest.writeString(this.electricOrderSerial);
    }

    protected PayModeEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.payModeId = in.readString();
        this.orderId = in.readString();
        this.paymentId = in.readString();
        this.paymentName = in.readString();
        this.paymentType = (Integer) in.readValue(Integer.class.getClassLoader());
        this.payMoney = (Float) in.readValue(Float.class.getClassLoader());
        this.payBalance = (Float) in.readValue(Float.class.getClassLoader());
        this.payTime = (Long) in.readValue(Long.class.getClassLoader());
        this.isJoinOrderPay = (Integer) in.readValue(Integer.class.getClassLoader());
        this.electricOrderSerial = in.readString();
    }

    public static final Parcelable.Creator<PayModeEntity> CREATOR = new Parcelable.Creator<PayModeEntity>() {
        @Override
        public PayModeEntity createFromParcel(Parcel source) {
            return new PayModeEntity(source);
        }

        @Override
        public PayModeEntity[] newArray(int size) {
            return new PayModeEntity[size];
        }
    };
}
