package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.MakeVo;

/**
 * Entity mapped to table "PRACTICE_ENTITY".
 */
public class PracticeEntity {

    private Long id;
    /** Not-null value. */
    private String practiceId;
    private String practiceName;

    public PracticeEntity() {
    }

    public PracticeEntity(Long id) {
        this.id = id;
    }

    public PracticeEntity(Long id, String practiceId, String practiceName) {
        this.id = id;
        this.practiceId = practiceId;
        this.practiceName = practiceName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPracticeId() {
        return practiceId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPracticeId(String practiceId) {
        this.practiceId = practiceId;
    }

    public String getPracticeName() {
        return practiceName;
    }

    public void setPracticeName(String practiceName) {
        this.practiceName = practiceName;
    }

    public PracticeEntity(MakeVo make){
        this.practiceId = make.getId();
        this.practiceName = make.getName();
        Log.d("###", "做法: "+this.toString());
    }

    @Override
    public String toString() {
        return "PracticeEntity{" +
                "id=" + id +
                ", practiceId='" + practiceId + '\'' +
                ", practiceName='" + practiceName + '\'' +
                '}';
    }

    public static ResultObjectBuilder<PracticeEntity> builder = new ResultObjectBuilder<PracticeEntity>() {
        @Override
        public PracticeEntity build(ResultSet rs) throws SQLException {
            PracticeEntity practiceEntity = new PracticeEntity();
            practiceEntity.setPracticeId(rs.getString("c_id"));
            practiceEntity.setPracticeName(rs.getString("c_name"));
            return practiceEntity;
        }
    };

}
