package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

/**
 * Entity mapped to table "PRINTER_FAILED_HISTORY_ENTITY".
 */
public class PrinterFailedHistoryEntity {

    private Long id;
    /**
     * Not-null value.
     */
    private String printerFailedHistoryId;
    private String printKitchenId;
    private String orderId;
    private Long printTime;
    private String printDishType;
    private String printDish;
    private Integer printStatus;
    private Integer printType;

    public PrinterFailedHistoryEntity() {
    }

    public PrinterFailedHistoryEntity(Long id) {
        this.id = id;
    }

    public PrinterFailedHistoryEntity(Long id, String printerFailedHistoryId, String printKitchenId, String orderId, Long printTime, String printDishType, String printDish, Integer printStatus, Integer printType) {
        this.id = id;
        this.printerFailedHistoryId = printerFailedHistoryId;
        this.printKitchenId = printKitchenId;
        this.orderId = orderId;
        this.printTime = printTime;
        this.printDishType = printDishType;
        this.printDish = printDish;
        this.printStatus = printStatus;
        this.printType = printType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getPrinterFailedHistoryId() {
        return printerFailedHistoryId;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setPrinterFailedHistoryId(String printerFailedHistoryId) {
        this.printerFailedHistoryId = printerFailedHistoryId;
    }

    public String getPrintKitchenId() {
        return printKitchenId;
    }

    public void setPrintKitchenId(String printKitchenId) {
        this.printKitchenId = printKitchenId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public Long getPrintTime() {
        return printTime;
    }

    public void setPrintTime(Long printTime) {
        this.printTime = printTime;
    }

    public String getPrintDishType() {
        return printDishType;
    }

    public void setPrintDishType(String printDishType) {
        this.printDishType = printDishType;
    }

    public String getPrintDish() {
        return printDish;
    }

    public String getPrintDishStr() {
        if (printDish != null && printDish.length() > 0) {
            String[] printDishes = printDish.split("、");
            for (String printDishStr :
                    printDishes) {
                printDishStr.replace("\n", "");
            }
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < printDishes.length; i++) {
                sb.append(printDishes[i] + "；");
            }
            String s = sb.toString();
            Log.d("###", "打印记录：" + printDish);
            return s;
        } else {
            return printDish;
        }
    }

    public String[] getPrintDishArray() {
        try {
            if (printDish != null && printDish.length() > 0) {
                String[] printDishes = printDish.split("、");
                return printDishes;
            } else {
                return new String[0];
            }
        } catch (Exception e) {
            return new String[0];
        }
    }

    public void setPrintDish(String printDish) {
        this.printDish = printDish;
    }

    public Integer getPrintStatus() {
        return printStatus;
    }

    public void setPrintStatus(Integer printStatus) {
        this.printStatus = printStatus;
    }

    public Integer getPrintType() {
        return printType;
    }

    public void setPrintType(Integer printType) {
        this.printType = printType;
    }

}
