package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.KitchenClassifyVo;

/**
 * Entity mapped to table "PRINT_KITCHEN_CLASSIFY_ENTITY".
 */
public class PrintKitchenClassifyEntity {

    private Long id;
    /** Not-null value. */
    private String printKitchenId;
    private String dishTypeId;
    private String dishTypeName;

    public PrintKitchenClassifyEntity() {
    }

    public PrintKitchenClassifyEntity(Long id) {
        this.id = id;
    }

    public PrintKitchenClassifyEntity(Long id, String printKitchenId, String dishTypeId, String dishTypeName) {
        this.id = id;
        this.printKitchenId = printKitchenId;
        this.dishTypeId = dishTypeId;
        this.dishTypeName = dishTypeName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPrintKitchenId() {
        return printKitchenId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPrintKitchenId(String printKitchenId) {
        this.printKitchenId = printKitchenId;
    }

    public String getDishTypeId() {
        return dishTypeId;
    }

    public void setDishTypeId(String dishTypeId) {
        this.dishTypeId = dishTypeId;
    }

    public String getDishTypeName() {
        return dishTypeName;
    }

    public void setDishTypeName(String dishTypeName) {
        this.dishTypeName = dishTypeName;
    }

    public PrintKitchenClassifyEntity(KitchenClassifyVo kitchenClassifyModel){
        this.printKitchenId = kitchenClassifyModel.getKitchenId();
        this.dishTypeId = kitchenClassifyModel.getGoodsTypeId();
        this.dishTypeName = kitchenClassifyModel.getGoodsTypeName();
        Log.d("###", "厨打分类: "+toString());
    }

    public static ResultObjectBuilder<PrintKitchenClassifyEntity> builder = new ResultObjectBuilder<PrintKitchenClassifyEntity>() {
        @Override
        public PrintKitchenClassifyEntity build(ResultSet rs) throws SQLException {
            PrintKitchenClassifyEntity printKitchenClassifyEntity = new PrintKitchenClassifyEntity();
            printKitchenClassifyEntity.setPrintKitchenId(rs.getString("c_kitchen"));
            printKitchenClassifyEntity.setDishTypeId(rs.getString("c_goods_type_id"));
            printKitchenClassifyEntity.setDishTypeName(rs.getString("c_goods_type_name"));

            return printKitchenClassifyEntity;
        }
    };

    @Override
    public String toString() {
        return "PrintKitchenClassifyEntity{" +
                "id=" + id +
                ", printKitchenId='" + printKitchenId + '\'' +
                ", dishTypeId='" + dishTypeId + '\'' +
                ", dishTypeName='" + dishTypeName + '\'' +
                '}';
    }
}
