package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.RoleVo;

/**
 * Entity mapped to table "RANK_ENTITY".
 */
public class RankEntity {

    private Long id;
    /** Not-null value. */
    private String rankId;
    private String rankName;

    public RankEntity() {
    }

    public RankEntity(Long id) {
        this.id = id;
    }

    public RankEntity(Long id, String rankId, String rankName) {
        this.id = id;
        this.rankId = rankId;
        this.rankName = rankName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRankId() {
        return rankId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRankId(String rankId) {
        this.rankId = rankId;
    }

    public String getRankName() {
        return rankName;
    }

    public void setRankName(String rankName) {
        this.rankName = rankName;
    }

    public RankEntity(RoleVo roleModel){
        this.rankId = roleModel.getId();
        this.rankName = roleModel.getName();
    }

    public static ResultObjectBuilder<RankEntity> builder = new ResultObjectBuilder<RankEntity>() {
        @Override
        public RankEntity build(ResultSet rs) throws SQLException {
            RankEntity rankEntity = new RankEntity();
            rankEntity.setRankId("c_id");
            rankEntity.setRankName("c_name");
            return rankEntity;
        }
    };

}
