package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ROOM_ENTITY".
 */
public class RoomEntity {

    private Long id;
    /** Not-null value. */
    private String roomId;
    private String takeoutId;
    private String employeeId;
    private Long roomStartTime;
    private Long roomEndTime;

    public RoomEntity() {
    }

    public RoomEntity(Long id) {
        this.id = id;
    }

    public RoomEntity(Long id, String roomId, String takeoutId, String employeeId, Long roomStartTime, Long roomEndTime) {
        this.id = id;
        this.roomId = roomId;
        this.takeoutId = takeoutId;
        this.employeeId = employeeId;
        this.roomStartTime = roomStartTime;
        this.roomEndTime = roomEndTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getRoomId() {
        return roomId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    public String getTakeoutId() {
        return takeoutId;
    }

    public void setTakeoutId(String takeoutId) {
        this.takeoutId = takeoutId;
    }

    public String getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public Long getRoomStartTime() {
        return roomStartTime;
    }

    public void setRoomStartTime(Long roomStartTime) {
        this.roomStartTime = roomStartTime;
    }

    public Long getRoomEndTime() {
        return roomEndTime;
    }

    public void setRoomEndTime(Long roomEndTime) {
        this.roomEndTime = roomEndTime;
    }

}
