package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "SCHEDULE_ENTITY".
 */
public class ScheduleEntity implements Parcelable {

    private Long id;
    /** Not-null value. */
    private String scheduleId;
    private String orderId;
    private String guestName;
    private String guestPhone;
    private String tableId;
    private Long mealTime;
    private Integer mealPeople;
    private Integer isOrdered;
    private Integer scheduleFrom;
    private String scheduleMark;
    private Integer scheduleStatus;

    public ScheduleEntity() {
    }

    public ScheduleEntity(Long id) {
        this.id = id;
    }

    public ScheduleEntity(Long id, String scheduleId, String orderId, String guestName, String guestPhone, String tableId, Long mealTime, Integer mealPeople, Integer isOrdered, Integer scheduleFrom, String scheduleMark, Integer scheduleStatus) {
        this.id = id;
        this.scheduleId = scheduleId;
        this.orderId = orderId;
        this.guestName = guestName;
        this.guestPhone = guestPhone;
        this.tableId = tableId;
        this.mealTime = mealTime;
        this.mealPeople = mealPeople;
        this.isOrdered = isOrdered;
        this.scheduleFrom = scheduleFrom;
        this.scheduleMark = scheduleMark;
        this.scheduleStatus = scheduleStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getScheduleId() {
        return scheduleId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setScheduleId(String scheduleId) {
        this.scheduleId = scheduleId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getGuestName() {
        return guestName;
    }

    public void setGuestName(String guestName) {
        this.guestName = guestName;
    }

    public String getGuestPhone() {
        return guestPhone;
    }

    public void setGuestPhone(String guestPhone) {
        this.guestPhone = guestPhone;
    }

    public String getTableId() {
        return tableId;
    }

    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

    public Long getMealTime() {
        return mealTime;
    }

    public void setMealTime(Long mealTime) {
        this.mealTime = mealTime;
    }

    public Integer getMealPeople() {
        return mealPeople;
    }

    public void setMealPeople(Integer mealPeople) {
        this.mealPeople = mealPeople;
    }

    public Integer getIsOrdered() {
        return isOrdered;
    }

    public void setIsOrdered(Integer isOrdered) {
        this.isOrdered = isOrdered;
    }

    public Integer getScheduleFrom() {
        return scheduleFrom;
    }

    public void setScheduleFrom(Integer scheduleFrom) {
        this.scheduleFrom = scheduleFrom;
    }

    public String getScheduleMark() {
        return scheduleMark;
    }

    public void setScheduleMark(String scheduleMark) {
        this.scheduleMark = scheduleMark;
    }

    public Integer getScheduleStatus() {
        return scheduleStatus;
    }

    public void setScheduleStatus(Integer scheduleStatus) {
        this.scheduleStatus = scheduleStatus;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.scheduleId);
        dest.writeString(this.orderId);
        dest.writeString(this.guestName);
        dest.writeString(this.guestPhone);
        dest.writeString(this.tableId);
        dest.writeValue(this.mealTime);
        dest.writeValue(this.mealPeople);
        dest.writeValue(this.isOrdered);
        dest.writeValue(this.scheduleFrom);
        dest.writeString(this.scheduleMark);
        dest.writeValue(this.scheduleStatus);
    }

    protected ScheduleEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.scheduleId = in.readString();
        this.orderId = in.readString();
        this.guestName = in.readString();
        this.guestPhone = in.readString();
        this.tableId = in.readString();
        this.mealTime = (Long) in.readValue(Long.class.getClassLoader());
        this.mealPeople = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isOrdered = (Integer) in.readValue(Integer.class.getClassLoader());
        this.scheduleFrom = (Integer) in.readValue(Integer.class.getClassLoader());
        this.scheduleMark = in.readString();
        this.scheduleStatus = (Integer) in.readValue(Integer.class.getClassLoader());
    }

    public static final Parcelable.Creator<ScheduleEntity> CREATOR = new Parcelable.Creator<ScheduleEntity>() {
        @Override
        public ScheduleEntity createFromParcel(Parcel source) {
            return new ScheduleEntity(source);
        }

        @Override
        public ScheduleEntity[] newArray(int size) {
            return new ScheduleEntity[size];
        }
    };
}
