package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.ShopTimeVo;

/**
 * Entity mapped to table "SHOP_TIME_ENTITY".
 */
public class ShopTimeEntity {

    private Long id;
    private String partnerCode;
    private Integer shopDayType;
    private String shopEndTime;

    public ShopTimeEntity() {
    }

    public ShopTimeEntity(Long id) {
        this.id = id;
    }

    public ShopTimeEntity(Long id, String partnerCode, Integer shopDayType, String shopEndTime) {
        this.id = id;
        this.partnerCode = partnerCode;
        this.shopDayType = shopDayType;
        this.shopEndTime = shopEndTime;
    }

    public ShopTimeEntity(ShopTimeVo vo){
        this.shopDayType = vo.getType();
        this.shopEndTime = vo.getEndTime();
        Log.d("###", "ShopTimeEntity: "+shopEndTime);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPartnerCode() {
        return partnerCode;
    }

    public void setPartnerCode(String partnerCode) {
        this.partnerCode = partnerCode;
    }

    public Integer getShopDayType() {
        return shopDayType;
    }

    public void setShopDayType(Integer shopDayType) {
        this.shopDayType = shopDayType;
    }

    public String getShopEndTime() {
        return shopEndTime;
    }

    public void setShopEndTime(String shopEndTime) {
        this.shopEndTime = shopEndTime;
    }

    public static ResultObjectBuilder<ShopTimeEntity> builder = new ResultObjectBuilder<ShopTimeEntity>() {
        @Override
        public ShopTimeEntity build(ResultSet rs) throws SQLException {
            ShopTimeEntity shopTimeEntity = new ShopTimeEntity();
            shopTimeEntity.setShopDayType(rs.getInt("c_type"));
            shopTimeEntity.setShopEndTime(rs.getString("c_end_time"));
            shopTimeEntity.setPartnerCode(rs.getString("c_partner_code"));
            return shopTimeEntity;
        }
    };

}
