package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import java.sql.ResultSet;
import java.sql.SQLException;

import jufeng.juyancash.jdbc.ResultObjectBuilder;
import jufeng.juyancash.syncdata.ShopMealsVo;

/**
 * Entity mapped to table "SHOP_MEALS_ENTITY".
 */
public class ShopMealsEntity {

    private Long id;
    private String partnerCode;
    private Integer mealsState;
    private String mealsStartTime;
    private String mealsRemindTime;

    public ShopMealsEntity() {
    }

    public ShopMealsEntity(Long id) {
        this.id = id;
    }

    public ShopMealsEntity(Long id, String partnerCode, Integer mealsState, String mealsStartTime, String mealsRemindTime) {
        this.id = id;
        this.partnerCode = partnerCode;
        this.mealsState = mealsState;
        this.mealsStartTime = mealsStartTime;
        this.mealsRemindTime = mealsRemindTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPartnerCode() {
        return partnerCode;
    }

    public void setPartnerCode(String partnerCode) {
        this.partnerCode = partnerCode;
    }

    public Integer getMealsState() {
        return mealsState;
    }

    public void setMealsState(Integer mealsState) {
        this.mealsState = mealsState;
    }

    public String getMealsStartTime() {
        return mealsStartTime;
    }

    public void setMealsStartTime(String mealsStartTime) {
        this.mealsStartTime = mealsStartTime;
    }

    public String getMealsRemindTime() {
        return mealsRemindTime;
    }

    public void setMealsRemindTime(String mealsRemindTime) {
        this.mealsRemindTime = mealsRemindTime;
    }

    @Override
    public String toString() {
        return "ShopMealsEntity{" +
                "id=" + id +
                ", partnerCode='" + partnerCode + '\'' +
                ", mealsState=" + mealsState +
                ", mealsStartTime='" + mealsStartTime + '\'' +
                ", mealsRemindTime='" + mealsRemindTime + '\'' +
                '}';
    }

    public ShopMealsEntity(ShopMealsVo shopMeals){
        this.mealsState = shopMeals.getState();
        this.mealsStartTime = shopMeals.getMealsTime();
        this.mealsRemindTime = shopMeals.getRemindTime();
    }

    public static ResultObjectBuilder<ShopMealsEntity> builder = new ResultObjectBuilder<ShopMealsEntity>() {
        @Override
        public ShopMealsEntity build(ResultSet rs) throws SQLException {
            ShopMealsEntity shopMealsEntity = new ShopMealsEntity();
            shopMealsEntity.setMealsState(rs.getInt("c_state"));
            shopMealsEntity.setMealsStartTime(rs.getString("c_meals_time"));
            shopMealsEntity.setMealsRemindTime(rs.getString("c_remind_time"));
            Log.d("###", "build: "+shopMealsEntity.toString());
            return shopMealsEntity;
        }
    };
}
