package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import jufeng.juyancash.syncdata.PaymentVo;

/**
 * Entity mapped to table "SHOP_PAYMENT_ENTITY".
 */
public class ShopPaymentEntity extends Payment{

    private Long id;
    /** Not-null value. */
    private String paymentId;
    private String partnerCode;
    private Integer paymentType;
    private String paymentName;
    private Integer isSaleState;
    private Integer isOpenCashBox;
    private Integer isOpenScanGun;

    public ShopPaymentEntity() {
    }

    public ShopPaymentEntity(Long id) {
        this.id = id;
    }

    public ShopPaymentEntity(Long id, String paymentId, String partnerCode, Integer paymentType, String paymentName, Integer isSaleState, Integer isOpenCashBox, Integer isOpenScanGun) {
        this.id = id;
        this.paymentId = paymentId;
        this.partnerCode = partnerCode;
        this.paymentType = paymentType;
        this.paymentName = paymentName;
        this.isSaleState = isSaleState;
        this.isOpenCashBox = isOpenCashBox;
        this.isOpenScanGun = isOpenScanGun;
        setName(paymentName);
        setPayId(paymentId);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPaymentId() {
        return paymentId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    public String getPartnerCode() {
        return partnerCode;
    }

    public void setPartnerCode(String partnerCode) {
        this.partnerCode = partnerCode;
    }

    public Integer getPaymentType() {
        return paymentType;
    }

    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    public String getPaymentName() {
        return paymentName;
    }

    public void setPaymentName(String paymentName) {
        this.paymentName = paymentName;
    }

    public Integer getIsSaleState() {
        return isSaleState;
    }

    public void setIsSaleState(Integer isSaleState) {
        this.isSaleState = isSaleState;
    }

    public Integer getIsOpenCashBox() {
        return isOpenCashBox;
    }

    public void setIsOpenCashBox(Integer isOpenCashBox) {
        this.isOpenCashBox = isOpenCashBox;
    }

    public Integer getIsOpenScanGun() {
        return isOpenScanGun;
    }

    public void setIsOpenScanGun(Integer isOpenScanGun) {
        this.isOpenScanGun = isOpenScanGun;
    }

    public ShopPaymentEntity(PaymentVo paymentmode){
        this.paymentId = paymentmode.getId();
        this.paymentType = paymentmode.getType();
        this.paymentName = paymentmode.getName();
        this.isSaleState = paymentmode.getSale();
        this.isOpenCashBox = paymentmode.getCashbox();
        this.isOpenScanGun = paymentmode.getScanCode();
        Log.d("###", "支付方式："+toString());
    }

    @Override
    public String toString() {
        return "ShopPaymentEntity{" +
                "id=" + id +
                ", paymentId='" + paymentId + '\'' +
                ", partnerCode='" + partnerCode + '\'' +
                ", paymentType=" + paymentType +
                ", paymentName='" + paymentName + '\'' +
                ", isSaleState=" + isSaleState +
                ", isOpenCashBox=" + isOpenCashBox +
                ", isOpenScanGun=" + isOpenScanGun +
                '}';
    }
}
