package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "SOME_DISCOUNT_GOODS_ENTITY".
 */
public class SomeDiscountGoodsEntity implements Parcelable {

    private Long id;
    /** Not-null value. */
    private String someDiscountGoodsId;
    private String discountHistoryId;
    private String orderDishId;
    private String dishId;

    public SomeDiscountGoodsEntity() {
    }

    public SomeDiscountGoodsEntity(Long id) {
        this.id = id;
    }

    public SomeDiscountGoodsEntity(Long id, String someDiscountGoodsId, String discountHistoryId, String orderDishId, String dishId) {
        this.id = id;
        this.someDiscountGoodsId = someDiscountGoodsId;
        this.discountHistoryId = discountHistoryId;
        this.orderDishId = orderDishId;
        this.dishId = dishId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSomeDiscountGoodsId() {
        return someDiscountGoodsId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSomeDiscountGoodsId(String someDiscountGoodsId) {
        this.someDiscountGoodsId = someDiscountGoodsId;
    }

    public String getDiscountHistoryId() {
        return discountHistoryId;
    }

    public void setDiscountHistoryId(String discountHistoryId) {
        this.discountHistoryId = discountHistoryId;
    }

    public String getOrderDishId() {
        return orderDishId;
    }

    public void setOrderDishId(String orderDishId) {
        this.orderDishId = orderDishId;
    }

    public String getDishId() {
        return dishId;
    }

    public void setDishId(String dishId) {
        this.dishId = dishId;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.someDiscountGoodsId);
        dest.writeString(this.discountHistoryId);
        dest.writeString(this.orderDishId);
        dest.writeString(this.dishId);
    }

    protected SomeDiscountGoodsEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.someDiscountGoodsId = in.readString();
        this.discountHistoryId = in.readString();
        this.orderDishId = in.readString();
        this.dishId = in.readString();
    }

    public static final Parcelable.Creator<SomeDiscountGoodsEntity> CREATOR = new Parcelable.Creator<SomeDiscountGoodsEntity>() {
        @Override
        public SomeDiscountGoodsEntity createFromParcel(Parcel source) {
            return new SomeDiscountGoodsEntity(source);
        }

        @Override
        public SomeDiscountGoodsEntity[] newArray(int size) {
            return new SomeDiscountGoodsEntity[size];
        }
    };
}
