package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "STORE_MESSAGE_ENTITY".
 */
public class StoreMessageEntity implements Parcelable {

    private Long id;
    /** Not-null value. */
    private String storeMessageId;
    private String storeTitle;
    private String storeTime;
    private String storeContent;
    private String storeImgUrl;
    private Integer isRead;

    public StoreMessageEntity() {
    }

    public StoreMessageEntity(Long id) {
        this.id = id;
    }

    public StoreMessageEntity(Long id, String storeMessageId, String storeTitle, String storeTime, String storeContent, String storeImgUrl, Integer isRead) {
        this.id = id;
        this.storeMessageId = storeMessageId;
        this.storeTitle = storeTitle;
        this.storeTime = storeTime;
        this.storeContent = storeContent;
        this.storeImgUrl = storeImgUrl;
        this.isRead = isRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getStoreMessageId() {
        return storeMessageId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStoreMessageId(String storeMessageId) {
        this.storeMessageId = storeMessageId;
    }

    public String getStoreTitle() {
        return storeTitle;
    }

    public void setStoreTitle(String storeTitle) {
        this.storeTitle = storeTitle;
    }

    public String getStoreTime() {
        return storeTime;
    }

    public void setStoreTime(String storeTime) {
        this.storeTime = storeTime;
    }

    public String getStoreContent() {
        return storeContent;
    }

    public void setStoreContent(String storeContent) {
        this.storeContent = storeContent;
    }

    public String getStoreImgUrl() {
        return storeImgUrl;
    }

    public void setStoreImgUrl(String storeImgUrl) {
        this.storeImgUrl = storeImgUrl;
    }

    public Integer getIsRead() {
        return isRead;
    }

    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.storeMessageId);
        dest.writeString(this.storeTitle);
        dest.writeString(this.storeTime);
        dest.writeString(this.storeContent);
        dest.writeString(this.storeImgUrl);
        dest.writeValue(this.isRead);
    }

    protected StoreMessageEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.storeMessageId = in.readString();
        this.storeTitle = in.readString();
        this.storeTime = in.readString();
        this.storeContent = in.readString();
        this.storeImgUrl = in.readString();
        this.isRead = (Integer) in.readValue(Integer.class.getClassLoader());
    }

    public static final Parcelable.Creator<StoreMessageEntity> CREATOR = new Parcelable.Creator<StoreMessageEntity>() {
        @Override
        public StoreMessageEntity createFromParcel(Parcel source) {
            return new StoreMessageEntity(source);
        }

        @Override
        public StoreMessageEntity[] newArray(int size) {
            return new StoreMessageEntity[size];
        }
    };
}
