package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;
import android.util.Log;

import jufeng.juyancash.syncdata.DeskVo;


/**
 * Entity mapped to table "TABLE_ENTITY".
 */
public class TableEntity implements Parcelable {
    public static int STATUS0 = 0;
    public static int STATUS1 = 1;
    public static int STATUS2 = 2;
    private Long id;
    /** Not-null value. */
    private String tableId;
    private String areaId;
    /** Not-null value. */
    private String tableName;
    private String tableCode;
    private Integer tableType;
    private Integer tableSeat;
    private Integer tableStatus;
    private Integer isLock;

    public TableEntity() {
    }

    public TableEntity(Long id) {
        this.id = id;
    }

    public TableEntity(Long id, String tableId, String areaId, String tableName, String tableCode, Integer tableType, Integer tableSeat, Integer tableStatus, Integer isLock) {
        this.id = id;
        this.tableId = tableId;
        this.areaId = areaId;
        this.tableName = tableName;
        this.tableCode = tableCode;
        this.tableType = tableType;
        this.tableSeat = tableSeat;
        this.tableStatus = tableStatus;
        this.isLock = isLock;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTableId() {
        return tableId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

    public String getAreaId() {
        return areaId;
    }

    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /** Not-null value. */
    public String getTableName() {
        return tableName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getTableCode() {
        return tableCode;
    }

    public void setTableCode(String tableCode) {
        this.tableCode = tableCode;
    }

    public Integer getTableType() {
        return tableType;
    }

    public void setTableType(Integer tableType) {
        this.tableType = tableType;
    }

    public Integer getTableSeat() {
        return tableSeat;
    }

    public void setTableSeat(Integer tableSeat) {
        this.tableSeat = tableSeat;
    }

    public Integer getTableStatus() {
        return tableStatus;
    }

    public void setTableStatus(Integer tableStatus) {
        this.tableStatus = tableStatus;
    }

    public Integer getIsLock() {
        return isLock;
    }

    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }

    public TableEntity(DeskVo deskModel){
        this.tableId = deskModel.getId();
        this.areaId = deskModel.getAreaId();
        this.tableName = deskModel.getName();
        this.tableCode = deskModel.getCode();
        this.tableType = deskModel.getType();
        this.tableSeat = deskModel.getNum();
        this.tableStatus = 0;
        this.isLock = 0;
        Log.d("###", "桌位："+this.toString());
    }

    @Override
    public String toString() {
        return "TableEntity{" +
                "id=" + id +
                ", tableId='" + tableId + '\'' +
                ", areaId='" + areaId + '\'' +
                ", tableName='" + tableName + '\'' +
                ", tableCode='" + tableCode + '\'' +
                ", tableType=" + tableType +
                ", tableSeat=" + tableSeat +
                ", tableStatus=" + tableStatus +
                ", isLock=" + isLock +
                '}';
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.tableId);
        dest.writeString(this.areaId);
        dest.writeString(this.tableName);
        dest.writeString(this.tableCode);
        dest.writeValue(this.tableType);
        dest.writeValue(this.tableSeat);
        dest.writeValue(this.tableStatus);
        dest.writeValue(this.isLock);
    }

    protected TableEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.tableId = in.readString();
        this.areaId = in.readString();
        this.tableName = in.readString();
        this.tableCode = in.readString();
        this.tableType = (Integer) in.readValue(Integer.class.getClassLoader());
        this.tableSeat = (Integer) in.readValue(Integer.class.getClassLoader());
        this.tableStatus = (Integer) in.readValue(Integer.class.getClassLoader());
        this.isLock = (Integer) in.readValue(Integer.class.getClassLoader());
    }

    public static final Parcelable.Creator<TableEntity> CREATOR = new Parcelable.Creator<TableEntity>() {
        @Override
        public TableEntity createFromParcel(Parcel source) {
            return new TableEntity(source);
        }

        @Override
        public TableEntity[] newArray(int size) {
            return new TableEntity[size];
        }
    };
}
