package jufeng.juyancash.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO four table "TAOCAN_TYPE_ENTITY".
*/
public class TaocanTypeEntityDao extends AbstractDao<TaocanTypeEntity, Long> {

    public static final String TABLENAME = "TAOCAN_TYPE_ENTITY";

    /**
     * Properties of entity TaocanTypeEntity.<br/>
     * Can be used four QueryBuilder and four referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TaocanTypeId = new Property(1, String.class, "taocanTypeId", false, "TAOCAN_TYPE_ID");
        public final static Property TaocanTypeName = new Property(2, String.class, "taocanTypeName", false, "TAOCAN_TYPE_NAME");
        public final static Property TaocanTypeCode = new Property(3, String.class, "taocanTypeCode", false, "TAOCAN_TYPE_CODE");
        public final static Property IsHasParent = new Property(4, Integer.class, "isHasParent", false, "IS_HAS_PARENT");
        public final static Property ParentId = new Property(5, String.class, "parentId", false, "PARENT_ID");
        public final static Property IsSaleParent = new Property(6, Integer.class, "isSaleParent", false, "IS_SALE_PARENT");
        public final static Property SaleParentId = new Property(7, String.class, "saleParentId", false, "SALE_PARENT_ID");
    }


    public TaocanTypeEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TaocanTypeEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TAOCAN_TYPE_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"TAOCAN_TYPE_ID\" TEXT NOT NULL UNIQUE ," + // 1: taocanTypeId
                "\"TAOCAN_TYPE_NAME\" TEXT," + // 2: taocanTypeName
                "\"TAOCAN_TYPE_CODE\" TEXT," + // 3: taocanTypeCode
                "\"IS_HAS_PARENT\" INTEGER," + // 4: isHasParent
                "\"PARENT_ID\" TEXT," + // 5: parentId
                "\"IS_SALE_PARENT\" INTEGER," + // 6: isSaleParent
                "\"SALE_PARENT_ID\" TEXT);"); // 7: saleParentId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TAOCAN_TYPE_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TaocanTypeEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTaocanTypeId());
 
        String taocanTypeName = entity.getTaocanTypeName();
        if (taocanTypeName != null) {
            stmt.bindString(3, taocanTypeName);
        }
 
        String taocanTypeCode = entity.getTaocanTypeCode();
        if (taocanTypeCode != null) {
            stmt.bindString(4, taocanTypeCode);
        }
 
        Integer isHasParent = entity.getIsHasParent();
        if (isHasParent != null) {
            stmt.bindLong(5, isHasParent);
        }
 
        String parentId = entity.getParentId();
        if (parentId != null) {
            stmt.bindString(6, parentId);
        }
 
        Integer isSaleParent = entity.getIsSaleParent();
        if (isSaleParent != null) {
            stmt.bindLong(7, isSaleParent);
        }
 
        String saleParentId = entity.getSaleParentId();
        if (saleParentId != null) {
            stmt.bindString(8, saleParentId);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TaocanTypeEntity readEntity(Cursor cursor, int offset) {
        TaocanTypeEntity entity = new TaocanTypeEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // taocanTypeId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // taocanTypeName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // taocanTypeCode
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // isHasParent
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // parentId
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // isSaleParent
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // saleParentId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TaocanTypeEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTaocanTypeId(cursor.getString(offset + 1));
        entity.setTaocanTypeName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTaocanTypeCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsHasParent(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setParentId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsSaleParent(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setSaleParentId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TaocanTypeEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TaocanTypeEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
