package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import jufeng.juyancash.syncdata.TaocanVo;

/**
 * Entity mapped to table "TAOCAN_ENTITY".
 */
public class TaocanEntity {

    private Long id;
    /** Not-null value. */
    private String taocanId;
    private String taocanTypeId;
    private String taocanName;
    private String taocanCode;
    private Float taocanPrice;
    private String unitName;
    private Integer isAbleDiscount;
    private Integer isAbleRetreat;
    private Integer isOnline;
    private String taocanCode1;

    public TaocanEntity() {
    }

    public TaocanEntity(Long id) {
        this.id = id;
    }

    public TaocanEntity(Long id, String taocanId, String taocanTypeId, String taocanName, String taocanCode, Float taocanPrice, String unitName, Integer isAbleDiscount, Integer isAbleRetreat, Integer isOnline, String taocanCode1) {
        this.id = id;
        this.taocanId = taocanId;
        this.taocanTypeId = taocanTypeId;
        this.taocanName = taocanName;
        this.taocanCode = taocanCode;
        this.taocanPrice = taocanPrice;
        this.unitName = unitName;
        this.isAbleDiscount = isAbleDiscount;
        this.isAbleRetreat = isAbleRetreat;
        this.isOnline = isOnline;
        this.taocanCode1 = taocanCode1;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTaocanId() {
        return taocanId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTaocanId(String taocanId) {
        this.taocanId = taocanId;
    }

    public String getTaocanTypeId() {
        return taocanTypeId;
    }

    public void setTaocanTypeId(String taocanTypeId) {
        this.taocanTypeId = taocanTypeId;
    }

    public String getTaocanName() {
        return taocanName;
    }

    public void setTaocanName(String taocanName) {
        this.taocanName = taocanName;
    }

    public String getTaocanCode() {
        return taocanCode;
    }

    public void setTaocanCode(String taocanCode) {
        this.taocanCode = taocanCode;
    }

    public Float getTaocanPrice() {
        return taocanPrice;
    }

    public void setTaocanPrice(Float taocanPrice) {
        this.taocanPrice = taocanPrice;
    }

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public Integer getIsAbleDiscount() {
        return isAbleDiscount;
    }

    public void setIsAbleDiscount(Integer isAbleDiscount) {
        this.isAbleDiscount = isAbleDiscount;
    }

    public Integer getIsAbleRetreat() {
        return isAbleRetreat;
    }

    public void setIsAbleRetreat(Integer isAbleRetreat) {
        this.isAbleRetreat = isAbleRetreat;
    }

    public Integer getIsOnline() {
        return isOnline;
    }

    public void setIsOnline(Integer isOnline) {
        this.isOnline = isOnline;
    }

    public String getTaocanCode1() {
        return taocanCode1;
    }

    public void setTaocanCode1(String taocanCode1) {
        this.taocanCode1 = taocanCode1;
    }

    public TaocanEntity(TaocanVo taocanModel){
        this.taocanId = taocanModel.getId();
        this.taocanName = taocanModel.getName();
        this.taocanCode = taocanModel.getCode();
        this.taocanPrice = ((float)taocanModel.getPrice())/100;
        this.unitName = taocanModel.getUnit();
        this.isAbleDiscount = taocanModel.getDiscount();
        this.isAbleRetreat = taocanModel.getTuicaiCheck();
        this.isOnline = taocanModel.getOnline();
        this.taocanTypeId = taocanModel.getTypeId();
        this.taocanCode1 = taocanModel.getCodeOne();
        Log.d("###", "套餐: "+toString());
    }

}
