package jufeng.juyancash.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO four table "TAOCAN_GROUP_ENTITY".
*/
public class TaocanGroupEntityDao extends AbstractDao<TaocanGroupEntity, Long> {

    public static final String TABLENAME = "TAOCAN_GROUP_ENTITY";

    /**
     * Properties of entity TaocanGroupEntity.<br/>
     * Can be used four QueryBuilder and four referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TaocanGroupId = new Property(1, String.class, "taocanGroupId", false, "TAOCAN_GROUP_ID");
        public final static Property TaocanId = new Property(2, String.class, "taocanId", false, "TAOCAN_ID");
        public final static Property TaocanGroupName = new Property(3, String.class, "taocanGroupName", false, "TAOCAN_GROUP_NAME");
        public final static Property SelectMode = new Property(4, Integer.class, "selectMode", false, "SELECT_MODE");
        public final static Property SelectCount = new Property(5, Integer.class, "selectCount", false, "SELECT_COUNT");
    }


    public TaocanGroupEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TaocanGroupEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TAOCAN_GROUP_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"TAOCAN_GROUP_ID\" TEXT NOT NULL UNIQUE ," + // 1: taocanGroupId
                "\"TAOCAN_ID\" TEXT," + // 2: taocanId
                "\"TAOCAN_GROUP_NAME\" TEXT," + // 3: taocanGroupName
                "\"SELECT_MODE\" INTEGER," + // 4: selectMode
                "\"SELECT_COUNT\" INTEGER);"); // 5: selectCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TAOCAN_GROUP_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TaocanGroupEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getTaocanGroupId());
 
        String taocanId = entity.getTaocanId();
        if (taocanId != null) {
            stmt.bindString(3, taocanId);
        }
 
        String taocanGroupName = entity.getTaocanGroupName();
        if (taocanGroupName != null) {
            stmt.bindString(4, taocanGroupName);
        }
 
        Integer selectMode = entity.getSelectMode();
        if (selectMode != null) {
            stmt.bindLong(5, selectMode);
        }
 
        Integer selectCount = entity.getSelectCount();
        if (selectCount != null) {
            stmt.bindLong(6, selectCount);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TaocanGroupEntity readEntity(Cursor cursor, int offset) {
        TaocanGroupEntity entity = new TaocanGroupEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // taocanGroupId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // taocanId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // taocanGroupName
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // selectMode
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // selectCount
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TaocanGroupEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTaocanGroupId(cursor.getString(offset + 1));
        entity.setTaocanId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTaocanGroupName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSelectMode(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setSelectCount(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TaocanGroupEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TaocanGroupEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
