package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "UPLOAD_DATA_ENTITY".
 */
public class UploadDataEntity {

    private Long id;
    /** Not-null value. */
    private String uploadDataId;
    private String orderId;
    private String dataId;
    private Integer dataType;
    private Integer isHand;
    private Integer count;
    private Long lastTime;

    public UploadDataEntity() {
    }

    public UploadDataEntity(Long id) {
        this.id = id;
    }

    public UploadDataEntity(Long id, String uploadDataId, String orderId, String dataId, Integer dataType, Integer isHand, Integer count, Long lastTime) {
        this.id = id;
        this.uploadDataId = uploadDataId;
        this.orderId = orderId;
        this.dataId = dataId;
        this.dataType = dataType;
        this.isHand = isHand;
        this.count = count;
        this.lastTime = lastTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUploadDataId() {
        return uploadDataId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUploadDataId(String uploadDataId) {
        this.uploadDataId = uploadDataId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getDataId() {
        return dataId;
    }

    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    public Integer getDataType() {
        return dataType;
    }

    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    public Integer getIsHand() {
        return isHand;
    }

    public void setIsHand(Integer isHand) {
        this.isHand = isHand;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Long getLastTime() {
        return lastTime;
    }

    public void setLastTime(Long lastTime) {
        this.lastTime = lastTime;
    }

}
