package jufeng.juyancash.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import jufeng.juyancash.syncdata.VipCardSetVo;

/**
 * Entity mapped to table "VIP_CARD_ENTITY".
 */
public class VipCardEntity {

    private Long id;
    private String vipCardId;
    private String vipCardName;
    private Integer vipCardType;
    private Integer vipCardDiscountType;
    private Integer vipCardDiscountRate;

    public VipCardEntity() {
    }

    public VipCardEntity(Long id) {
        this.id = id;
    }

    public VipCardEntity(Long id, String vipCardId, String vipCardName, Integer vipCardType, Integer vipCardDiscountType, Integer vipCardDiscountRate) {
        this.id = id;
        this.vipCardId = vipCardId;
        this.vipCardName = vipCardName;
        this.vipCardType = vipCardType;
        this.vipCardDiscountType = vipCardDiscountType;
        this.vipCardDiscountRate = vipCardDiscountRate;
    }

    public VipCardEntity(VipCardSetVo vo){
        this.vipCardId = vo.getId();
        this.vipCardName = vo.getVipName();
        this.vipCardType = vo.getCardType();
        this.vipCardDiscountType = vo.getDiscount();
        if(vo.getDiscount() == 0){
            //不打折
            this.vipCardDiscountRate = 100;
        }else{
            //打折
            this.vipCardDiscountRate = vo.getDiscountRate();
        }

        Log.d("###", "会员卡信息："+toString());
    }

    @Override
    public String toString() {
        return "VipCardEntity{" +
                "id=" + id +
                ", vipCardId='" + vipCardId + '\'' +
                ", vipCardName='" + vipCardName + '\'' +
                ", vipCardType=" + vipCardType +
                ", vipCardDiscountType=" + vipCardDiscountType +
                ", vipCardDiscountRate=" + vipCardDiscountRate +
                '}';
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVipCardId() {
        return vipCardId;
    }

    public void setVipCardId(String vipCardId) {
        this.vipCardId = vipCardId;
    }

    public String getVipCardName() {
        return vipCardName;
    }

    public void setVipCardName(String vipCardName) {
        this.vipCardName = vipCardName;
    }

    public Integer getVipCardType() {
        return vipCardType;
    }

    public void setVipCardType(Integer vipCardType) {
        this.vipCardType = vipCardType;
    }

    public Integer getVipCardDiscountType() {
        return vipCardDiscountType;
    }

    public void setVipCardDiscountType(Integer vipCardDiscountType) {
        this.vipCardDiscountType = vipCardDiscountType;
    }

    public Integer getVipCardDiscountRate() {
        return vipCardDiscountRate;
    }

    public void setVipCardDiscountRate(Integer vipCardDiscountRate) {
        this.vipCardDiscountRate = vipCardDiscountRate;
    }

}
